export function getTheme(id: any): {
    id: string;
    label: string;
    fonts: any[];
    vars: {
        "--bg"?: undefined;
        "--surface"?: undefined;
        "--surface-1"?: undefined;
        "--surface-2"?: undefined;
        "--surface-3"?: undefined;
        "--border"?: undefined;
        "--border-strong"?: undefined;
        "--muted"?: undefined;
        "--text"?: undefined;
        "--bright"?: undefined;
        "--accent"?: undefined;
        "--accent-dim"?: undefined;
        "--green"?: undefined;
        "--yellow"?: undefined;
        "--red"?: undefined;
        "--blue"?: undefined;
        "--purple"?: undefined;
        "--cyan"?: undefined;
        "--success"?: undefined;
        "--danger"?: undefined;
        "--warning"?: undefined;
        "--radius"?: undefined;
        "--radius-lg"?: undefined;
        "--font-mono"?: undefined;
    };
    css: string;
} | {
    id: string;
    label: string;
    fonts: string[];
    vars: {
        "--bg": string;
        "--surface": string;
        "--surface-1": string;
        "--surface-2": string;
        "--surface-3": string;
        "--border": string;
        "--border-strong": string;
        "--muted": string;
        "--text": string;
        "--bright": string;
        "--accent": string;
        "--accent-dim": string;
        "--green": string;
        "--yellow": string;
        "--red": string;
        "--blue": string;
        "--purple": string;
        "--cyan": string;
        "--success": string;
        "--danger": string;
        "--warning": string;
        "--radius": string;
        "--radius-lg": string;
        "--font-mono": string;
    };
    css: string;
};
/** Combined CSS for a theme: the token block + its scoped extras. */
export function themeStyle(theme: any): string;
export const DEFAULT_THEME: "default";
export const THEMES: ({
    id: string;
    label: string;
    fonts: any[];
    vars: {
        "--bg"?: undefined;
        "--surface"?: undefined;
        "--surface-1"?: undefined;
        "--surface-2"?: undefined;
        "--surface-3"?: undefined;
        "--border"?: undefined;
        "--border-strong"?: undefined;
        "--muted"?: undefined;
        "--text"?: undefined;
        "--bright"?: undefined;
        "--accent"?: undefined;
        "--accent-dim"?: undefined;
        "--green"?: undefined;
        "--yellow"?: undefined;
        "--red"?: undefined;
        "--blue"?: undefined;
        "--purple"?: undefined;
        "--cyan"?: undefined;
        "--success"?: undefined;
        "--danger"?: undefined;
        "--warning"?: undefined;
        "--radius"?: undefined;
        "--radius-lg"?: undefined;
        "--font-mono"?: undefined;
    };
    css: string;
} | {
    id: string;
    label: string;
    fonts: string[];
    vars: {
        "--bg": string;
        "--surface": string;
        "--surface-1": string;
        "--surface-2": string;
        "--surface-3": string;
        "--border": string;
        "--border-strong": string;
        "--muted": string;
        "--text": string;
        "--bright": string;
        "--accent": string;
        "--accent-dim": string;
        "--green": string;
        "--yellow": string;
        "--red": string;
        "--blue": string;
        "--purple": string;
        "--cyan": string;
        "--success": string;
        "--danger": string;
        "--warning": string;
        "--radius": string;
        "--radius-lg": string;
        "--font-mono": string;
    };
    css: string;
})[];
