"""abstract_hugpy_dev - transitional alias over the hugpy-* distributions.

GENERATED by tools/generate.py; do not edit by hand.

This package contains no implementation. Importing it installs a meta-path
finder that aliases every old ``abstract_hugpy_dev.<module>`` path to the same
module object in its new ``hugpy_*`` home (see RELOCATIONS.md), and re-exports
below every public name ``import abstract_hugpy_dev`` used to expose at top
level (monolith 0.1.266). Each group is independent: a missing optional
distribution only removes its own names.
"""

from __future__ import annotations

from ._relocations import install as _install_relocations
from ._relocations import aggregator_getattr as _aggregator_getattr

_install_relocations()

try:
    from importlib.metadata import version as _pkg_version

    __version__ = _pkg_version("abstract_hugpy_dev")
except Exception:  # uninstalled source run
    __version__ = "0.1.267.dev0"

# The old namespace installed the pure-Python pydantic shim before anything
# imported pydantic (phones without pydantic_core). Keep that contract.
try:
    from hugpy_platform.compat_pydantic import ensure_pydantic as _ensure_pydantic

    _ensure_pydantic()
except ImportError:  # hugpy-platform missing: nothing below will import either
    pass

# --- modules the old namespace exposed as attributes -----------------------
import argparse
import base64
import copy
import functools
import glob
import json
import logging
import os
import posixpath as osp
import re
import socket
import sys
import tempfile
import threading
import time
import traceback
import unicodedata
import urllib
import uuid
try:
    import bs4
except ImportError:  # bs4 not installed
    pass
try:
    import requests
except ImportError:  # requests not installed
    pass

# --- standard library names the old namespace re-exported ----------------
from _typing import NoDefault
from contextlib import contextmanager
from dataclasses import asdict, dataclass, field, fields
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import (
    AbstractSet,
    Any,
    AnyStr,
    AsyncGenerator,
    AsyncIterable,
    Awaitable,
    BinaryIO,
    ByteString,
    ChainMap,
    ClassVar,
    Collection,
    Concatenate,
    Container,
    Coroutine,
    Counter,
    DefaultDict,
    Deque,
    ForwardRef,
    FrozenSet,
    Generator,
    Generic,
    Hashable,
    IO,
    ItemsView,
    KeysView,
    LiteralString,
    MappingView,
    Match,
    MutableMapping,
    MutableSequence,
    MutableSet,
    NamedTuple,
    Never,
    NewType,
    NoReturn,
    NotRequired,
    OrderedDict,
    ParamSpec,
    ParamSpecArgs,
    ParamSpecKwargs,
    Pattern,
    Protocol,
    ReadOnly,
    Required,
    Reversible,
    Self,
    Set,
    SupportsAbs,
    SupportsBytes,
    SupportsComplex,
    SupportsFloat,
    SupportsIndex,
    SupportsInt,
    SupportsRound,
    Text,
    TextIO,
    TypeAlias,
    TypeAliasType,
    TypeGuard,
    TypeIs,
    TypeVar,
    TypeVarTuple,
    TypedDict,
    Unpack,
    ValuesView,
    assert_never,
    assert_type,
    cast,
    clear_overloads,
    dataclass_transform,
    final,
    get_args,
    get_origin,
    get_overloads,
    get_protocol_members,
    get_type_hints,
    is_protocol,
    is_typeddict,
    no_type_check,
    no_type_check_decorator,
    overload,
    override,
    reveal_type,
    runtime_checkable,
)
from urllib.parse import parse_qs, quote, unquote, urlparse, urlunparse
from uuid import uuid1

# --- third-party names the old namespace re-exported ---------------------
try:
    from PyPDF2 import PdfReader
except ImportError:  # PyPDF2 not installed
    pass
try:
    from abstract_essentials import (
        DATE_FORMAT,
        LOG_FORMAT,
        LOG_ROOT,
        LevelFilter,
        MEDIA_TYPES,
        MIME_TYPES,
        SafeFormatter,
        SingletonMeta,
        clean_invalid_newlines,
        combineList,
        compare_lists,
        derive_media_type,
        dump_if_json,
        eatAll,
        eatInner,
        eatOuter,
        ensure_nested_list,
        filter_json_list_values,
        find_keys,
        find_original_case,
        find_paths_to_key,
        flatten_json,
        get_abs_name_of_this,
        get_actual_number,
        get_any_value,
        get_base_name,
        get_caller,
        get_caller_dir,
        get_caller_path,
        get_current_path,
        get_desired_key_values,
        get_df,
        get_directory,
        get_dirlist,
        get_env_value,
        get_ext,
        get_file_name,
        get_file_parts,
        get_file_path,
        get_files,
        get_files_and_dirs,
        get_highest_value_obj,
        get_home_dir,
        get_home_folder,
        get_inputs,
        get_keys,
        get_lazy_attr,
        get_logFile,
        get_mime_type,
        get_only_kwargs,
        get_safe_basename,
        get_safe_dirname,
        get_safe_splitext,
        get_single_from_list,
        get_slash,
        get_sort,
        get_symetric_difference,
        get_value_from_path,
        is_dir,
        is_number,
        join_path,
        lazy_import,
        lazy_import_single,
        lazy_module,
        list_set,
        makeParams,
        make_key_map,
        make_list,
        make_list_add,
        make_list_it,
        makedirs,
        mkdirs,
        nullProxy,
        parse_url,
        prune_inputs,
        raw_create_dirs,
        read_any_file,
        read_directory,
        read_file_as_text,
        read_from_file,
        read_malformed_json,
        recursive_json_list,
        remove_from_list,
        run_pruned_func,
        safe_dump_to_file,
        safe_dump_to_json,
        safe_join,
        safe_json_loads,
        safe_list_return,
        safe_load_from_json,
        safe_read_from_json,
        sanitize_filename,
        save_df,
        split_text,
        try_json_loads,
        validate_file_path,
        write_to_file,
    )
except ImportError:  # abstract_essentials not installed
    pass
try:
    from annotated_types import Annotated, TYPE_CHECKING
except ImportError:  # annotated_types not installed
    pass
try:
    from bs4 import Sized
except ImportError:  # bs4 not installed
    pass
try:
    from filelock import Final
except ImportError:  # filelock not installed
    pass
try:
    from huggingface_hub import HfApi, RepoFile, hf_hub_download, snapshot_download
except ImportError:  # huggingface_hub not installed
    pass
try:
    from huggingface_hub.errors import HFValidationError, HfHubHTTPError
except ImportError:  # huggingface_hub not installed
    pass
try:
    from pydantic import (
        BaseModel,
        ConfigDict,
        Field,
        field_validator,
        model_serializer,
        model_validator,
    )
except ImportError:  # pydantic not installed
    pass

# --- hugpy-platform ------------------------------------------------------------
try:
    from hugpy_platform import FAILED, annotations
except ImportError:  # hugpy-platform missing or its optional dependency absent
    pass
try:
    from hugpy_platform.binaries import Iterable, Optional
except ImportError:  # hugpy-platform missing or its optional dependency absent
    pass
try:
    from hugpy_platform.constants import (
        CHAT_UPLOAD_DIR,
        DATASETS_DIR,
        DATASETS_HOME,
        DEFAULT_DEPTH_MODEL,
        DEFAULT_DETECT_MODEL,
        DEFAULT_EMBED_MODEL,
        DEFAULT_IMAGEGEN_MODEL,
        DEFAULT_IMG_CLASSIFY_MODEL,
        DEFAULT_KEYWORDS_MODEL,
        DEFAULT_LOCAL_FILES_ONLY,
        DEFAULT_MAX_TOKENS,
        DEFAULT_ROOT,
        DEFAULT_SEGMENT_MODEL,
        DEFAULT_SUMMARIZE_MODEL,
        DEFAULT_TEMPERATURE,
        DEFAULT_TIMEOUT,
        DEFAULT_TOP_P,
        DEFAULT_VISION_MODEL,
        DEFAULT_WHISPER_MODEL,
        DISK_AUTHORITATIVE,
        EXCLUDE_DIR_NAMES,
        EXCLUDE_DIR_PREFIXES,
        FINISH_REASONS,
        GGUF_QUANT,
        HF_CACHE,
        HF_HOME,
        HF_HUB_CACHE,
        HF_TOKEN,
        HF_TOKEN_ENV,
        HF_TOKEN_PATH,
        HUGGINGFACE_DOMAIN,
        HUGPY_AUTO_DOWNLOAD,
        HUGPY_MARKER,
        IDENTITIES_DIR,
        IDENTITIES_HOME,
        JOBSTATUS,
        LLAMA_HOST,
        Literal,
        MIN_INPUT_WORDS_DEFAULT,
        MODELS_DICT_PATH,
        MODELS_DIR,
        MODELS_DISCOVERY_PATH,
        MODELS_HOME,
        OVERLAY_ALLOWED,
        PATHS,
        PIP_CACHE_DIR,
        PROJECTS_DIR,
        PROJECTS_HOME,
        PROJECTS_PLACEMENT_PATH,
        ROLES,
        SOURCEKIND,
        TOKENIZER_SENTINEL_THRESHOLD,
        TORCH_HOME,
        UPLOADS_HOME,
        VISION_HOST,
        env_bool,
        read_stored_hf_token,
    )
except ImportError:  # hugpy-platform missing or its optional dependency absent
    pass
try:
    from hugpy_platform.except_utils import attempt, catching, caught, caught_block
except ImportError:  # hugpy-platform missing or its optional dependency absent
    pass
try:
    from hugpy_platform.module_imports import (
        get_easyocr,
        get_keybert,
        get_moviepy,
        get_paddleocr,
        get_pdf2image,
        get_pydub,
        get_pypdf2,
        get_pytesseract,
        get_sentence_transformers,
        get_spacy,
        get_speech_recognition,
        get_tiktoken,
        get_torch,
        get_transformers,
        get_whisper,
        is_available,
        require,
        require_peft,
    )
except ImportError:  # hugpy-platform missing or its optional dependency absent
    pass
try:
    from hugpy_platform.utils import (
        Dict,
        List,
        Tuple,
        config_exists,
        exists,
        extract_gguf_filename,
        find_keys_by_type,
        find_mmproj,
        get_base_64_image,
        get_config_in_dir,
        get_glob,
        get_guffs_in_dir,
        get_host,
        get_max_model_length,
        get_message,
        get_messages,
        get_name,
        get_parts,
        get_port,
        get_request_id,
        get_stat,
        get_target_name,
        get_unique_part,
        infer_framework,
        is_file,
        is_mmproj_file,
        itter_dir,
        make_request_id,
        merge_disk_over_registry,
        message_to_dict,
        messages_to_dicts,
        normalize_folder,
        require_file,
        safe_dtype_name,
        slugify,
        st_mtime,
        st_size,
        unique_path,
    )
except ImportError:  # hugpy-platform missing or its optional dependency absent
    pass
# --- hugpy-control -------------------------------------------------------------
try:
    from hugpy_control.bus import Iterator
except ImportError:  # hugpy-control missing or its optional dependency absent
    pass
try:
    from hugpy_control.shared import Callable, retry_on_emfile
except ImportError:  # hugpy-control missing or its optional dependency absent
    pass
# --- hugpy-storage -------------------------------------------------------------
try:
    from hugpy_storage.catalog_source import catalog_get, catalog_rows
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
try:
    from hugpy_storage.download_models import (
        download_dict_models,
        download_one,
        ensure_model,
        ensure_models,
        reap_orphaned_staging,
        record_downloaded_model,
        requested_file_missing,
        staged_bytes,
    )
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
try:
    from hugpy_storage.events import publish_catalog_changed
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
try:
    from hugpy_storage.huggingface_api import (
        HFAuditRow,
        audit_hf_snapshot,
        audit_hfs,
        confirm_all_links,
        download_missing_only,
        download_repo,
        get_huggingface_module_dir,
        get_huggingface_module_link,
        human_bytes,
        print_hf_audit,
    )
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
try:
    from hugpy_storage.hugpy_marker import (
        backfill_markers,
        detect_bnb_capable,
        detect_moe_capable,
        get_model_home,
        has_hugpy_marker,
        hub_id_for,
        list_gguf_quants,
        read_hugpy_marker,
        sync_marker_quants,
        write_hugpy_marker,
    )
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
try:
    from hugpy_storage.model_paths import (
        RUNTIME_FAMILIES,
        candidate_model_dirs,
        exclude_dirs,
        flat_destination,
        get_hub_id_from_directory,
        get_model_dirs,
        is_directory_excluded,
        is_model_dir,
        legacy_task_dirs,
        resolve_model_dir,
        resolve_task,
        route_destination,
        runtime_folder,
        safe_name,
        safe_path_part,
        split_hub_id,
    )
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
try:
    from hugpy_storage.model_presence import model_looks_downloaded
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
try:
    from hugpy_storage.providers import serve_path
except ImportError:  # hugpy-storage missing or its optional dependency absent
    pass
# --- hugpy-engine --------------------------------------------------------------
try:
    from hugpy_engine import HF_TASK_TO_TASKS, MEDIA_DEFAULTS, RUNNER_PAIRS, TASK_DEFAULTS
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.apis.call_api import (
        DEEPCODER_GENERATE_URL,
        DEEPCODER_URL,
        HUGPY_URL,
        call_and_code,
        call_generate,
        get_all_code,
        get_code,
        get_code_from_respose,
        get_prompt,
        get_response_dir,
        get_response_path,
        get_responses_dir,
        get_time_response_dir,
        make_response_dir,
        make_response_path,
        make_time_response_dir,
        postRequest,
        save_response,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.apis.get_module import (
        MODEL_REGISTRY,
        ResolverFn,
        build_resolver_chain,
        clean_hub_id,
        dataclass_fields,
        discover_model,
        discover_models,
        enrich,
        get_all_configs,
        get_config_from_folder,
        is_valid_repo_id,
        resolve_dir_declaration,
        resolve_hub_model_info,
        resolve_hugpy_marker,
        resolve_layout_path,
        resolve_local_config,
        resolve_local_tokenizer,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.backend import AsyncIterator, Mapping
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.categories import IMG2IMG_CAPABLE_FRAMEWORKS
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.chat_context import GenerateOnce, TokenCounter
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.chat_context.chat_context import (
        compact_chat_request,
        ctx_fit_chat_request,
        ctx_fit_keep_indices,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.chat_context.context_budget import (
        ContextBudget,
        compact_messages_to_budget,
        estimate_message_tokens,
        estimate_tokens,
        trim_content_to_token_budget,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.chat_context.unbounded import (
        GenerationOutcome,
        map_finish_reason,
        run_unbounded,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.config.main import (
        DEFAULT_PATHS,
        get_gguf_file,
        get_model_config,
        get_model_path,
        list_model_options,
        list_models,
        logger,
        resolve_hf_model_dir,
        resolve_model_source,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.config.models.models_config import (
        DEFAULT_MAX_TOKENS_LOCAL,
        MODEL_REGISTRY_DICT,
        TTS_TASK,
        assess_config,
        base_present,
        derive_model_config_row,
        get_assessed_model_config,
        get_model_registry,
        get_model_values,
        get_models_dict,
        media_default_state,
        media_state,
        media_states,
        merge_discovery_into_models,
        prune_model,
        refresh_registry,
        set_media_default,
        set_model_media,
        set_worker_boot_prewarm,
        set_worker_wildcard,
        unprune_model,
        update_model_config_dict,
        worker_boot_prewarm_state,
        worker_wildcard_state,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.config.models.models_default import (
        CHAT_MODELS_REGISTRY,
        DEFAULT_AGENT_BRAIN,
        DEFAULT_CONTEXT_TOKENS_BY_MODEL,
        EMBED_MODELS_REGISTRY,
        VISION_MODELS_REGISTRY,
        WHISPER_MODELS_REGISTRY,
        default_context_tokens_for_model,
        get_context_tokens,
        get_models_dict_by_names,
        get_models_dict_by_tasks,
        refresh_task_registries,
        replacement,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.dispatch.acquire import MODELS, acquire
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.dispatch.dispatch import (
        LoadRefusal,
        clear,
        ensure_headroom_for_load,
        evict,
        execute_chat_stream,
        execute_prompt,
        execute_prompt_stream,
        infer_arg_name,
        last_used_snapshot,
        loaded_disk_detail,
        loaded_model_keys,
        loading_model_keys,
        no_makeroom_active,
        normalize_prompt_kwargs,
        runner_for,
        set_evict_reason,
        set_evictable,
        set_fit_check,
        set_make_room,
        set_post_evict_hook,
        stream_runner,
        supported_task_keys,
        touch_model,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.generate import REGISTRY
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.generate.coder import (
        DeepCoder,
        StreamEvent,
        Union,
        deep_coder_generate,
        get_deep_coder,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.generate.config import (
        CancelStoppingCriteria,
        DeepCoderConfig,
        build_deepcoder_config,
        build_deepcoder_runtime,
        pick_device_and_dtype,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.generate.generate_runner import DeepCoderChatRunner
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.llama.runners.chat_runner import LlamaCppChatRunner
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.llama.runners.get import (
        LocalEngineUnavailable,
        clear_llama_runners,
        evict_llama_runner,
        get_llama_runner,
        loaded_runner_detail,
        slot_backed_model_keys,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.llama.runners.src.base_runner import LlamaCppBaseRunner
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.llama.runners.src.ccp_runner import LlamaCppRunner
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.llama.runners.src.python_runner import LlamaCppPythonRunner
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.llama.runners.src.shard_server import (
        ensure_shard_server,
        ensure_vision_server,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.model_classifier import (
        ADAPTER_TASK,
        NEEDS_CLASSIFICATION_TASK,
        adapter_refusal,
        classify_model_dir,
        is_speech_checkpoint_dir,
        needs_classification_refusal,
        pipeline_class_name,
        tasks_for_pipeline_class,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.peft_adapters import (
        ADAPTER_CONFIG_NAME,
        AdapterBaseUnavailable,
        MODEL_CONFIG_NAME,
        adapter_base_id,
        adapter_metadata_fields,
        adapter_peft_type,
        adapter_unserveable_reason,
        base_model_present,
        find_base_model_dir,
        has_standalone_config,
        is_adapter_dir,
        read_adapter_config,
        read_model_config,
        resolve_adapter_pair,
        standalone_load_refusal,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.placement import AsyncContextManager, ContextManager, Sequence
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.resolvers import EXTERNAL_TASK_RUNNERS
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.resolvers.model_resolver import (
        DEFAULT_CHAT_MODEL,
        Peer,
        ensure_staple_weights,
        external_runner_for,
        peer_for,
        resolve,
        resolve_model_key,
        validate_registry,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.resolvers.remote import (
        get_worker_provider,
        set_no_worker_diagnostic,
        set_placement_provider,
        set_worker_provider,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.schemas.chat_schemas import (
        ChatInput,
        ChatMessage,
        ChatRequest,
        ChatResult,
        merge_consecutive_messages,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.schemas.event_schemas import (
        DoneEvent,
        ErrorEvent,
        StatusEvent,
        TokenEvent,
    )
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.schemas.metadata_schemas import ModelMetadata
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.schemas.model_schemas import DeepCoderRuntime, MISSING, ModelConfig
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.schemas.runner_schemas import Runner
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.schemas.task_schemas import Resolution, TaskRequest, TaskResult, Type
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
try:
    from hugpy_engine.serve.serve import serve_endpoint, serve_model_name
except ImportError:  # hugpy-engine missing or its optional dependency absent
    pass
# --- hugpy-media ---------------------------------------------------------------
try:
    from hugpy_media.chunking import count_tokens, get_encoder, recursive_chunk
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.embed.embed_runner import FeatureExtractionRunner
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.imagegen.imagegen_runner import ImageGenRunner, Img2ImgRunner
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.imagegen.schemas import GeneratedImage, ImageGenRequest, ImageGenResult
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.keywords.keywords_runner import KeywordRunner
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.keywords.schemas import KeywordTaskRequest, KeywordTaskResult
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.schemas.embeded_schemas import EmbedRequest, EmbedResult
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.schemas.summarizer_schemas import (
        FinishReason,
        InputPolicy,
        SummarizeRequest,
        SummarizeResult,
        SummaryPreset,
        SummaryRequest,
    )
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.schemas.whisper_schemas import (
        FrameCandidate,
        FrameContext,
        MediaArtifactManifest,
        MediaWorkspace,
        TranscribeRequest,
        TranscribeResult,
        TranscribeSegment,
        TranscribeWord,
    )
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.summarizers.summarize_runner import SummarizeRunner
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.summarizers.summarizers import summarize
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.vision.schemas import VisionBackendConfig, VisionRequest, VisionResult
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.vision.vision_runner import VisionRunner
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.whisper_model.src.runner import WhisperRunner
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
try:
    from hugpy_media.whisper_model.src.stream import (
        extension_from_content_type,
        stream_url_to_temp_file,
        whisper_transcribe_url_stream,
    )
except ImportError:  # hugpy-media missing or its optional dependency absent
    pass
# --- hugpy-video ---------------------------------------------------------------
try:
    from hugpy_video.schemas.video_schemas import (
        FrameAnalysis,
        VideoAnalysisConfig,
        VideoAnalysisSummary,
    )
except ImportError:  # hugpy-video missing or its optional dependency absent
    pass

# not relocated: apis, config, constants, imports, init_imports, managers, models, schemas, src, standalone_utils, utils
#   These were the retired aggregator packages themselves (imports/, managers/,
#   utils/ ...). They resolve lazily through __getattr__ below as namespace
#   modules, e.g. ``abstract_hugpy_dev.managers.serve`` -> hugpy_engine.serve.

_SURFACE = (
    'ADAPTER_CONFIG_NAME', 'ADAPTER_TASK', 'AbstractSet', 'AdapterBaseUnavailable', 'Annotated', 'Any',
    'AnyStr', 'AsyncContextManager', 'AsyncGenerator', 'AsyncIterable', 'AsyncIterator', 'Awaitable',
    'BaseModel', 'BinaryIO', 'ByteString', 'CHAT_MODELS_REGISTRY', 'CHAT_UPLOAD_DIR', 'Callable',
    'CancelStoppingCriteria', 'ChainMap', 'ChatInput', 'ChatMessage', 'ChatRequest', 'ChatResult',
    'ClassVar', 'Collection', 'Concatenate', 'ConfigDict', 'Container', 'ContextBudget',
    'ContextManager', 'Coroutine', 'Counter', 'DATASETS_DIR', 'DATASETS_HOME', 'DATE_FORMAT',
    'DEEPCODER_GENERATE_URL', 'DEEPCODER_URL', 'DEFAULT_AGENT_BRAIN', 'DEFAULT_CHAT_MODEL', 'DEFAULT_CONTEXT_TOKENS_BY_MODEL', 'DEFAULT_DEPTH_MODEL',
    'DEFAULT_DETECT_MODEL', 'DEFAULT_EMBED_MODEL', 'DEFAULT_IMAGEGEN_MODEL', 'DEFAULT_IMG_CLASSIFY_MODEL', 'DEFAULT_KEYWORDS_MODEL', 'DEFAULT_LOCAL_FILES_ONLY',
    'DEFAULT_MAX_TOKENS', 'DEFAULT_MAX_TOKENS_LOCAL', 'DEFAULT_PATHS', 'DEFAULT_ROOT', 'DEFAULT_SEGMENT_MODEL', 'DEFAULT_SUMMARIZE_MODEL',
    'DEFAULT_TEMPERATURE', 'DEFAULT_TIMEOUT', 'DEFAULT_TOP_P', 'DEFAULT_VISION_MODEL', 'DEFAULT_WHISPER_MODEL', 'DISK_AUTHORITATIVE',
    'DeepCoder', 'DeepCoderChatRunner', 'DeepCoderConfig', 'DeepCoderRuntime', 'DefaultDict', 'Deque',
    'Dict', 'DoneEvent', 'EMBED_MODELS_REGISTRY', 'EXCLUDE_DIR_NAMES', 'EXCLUDE_DIR_PREFIXES', 'EXTERNAL_TASK_RUNNERS',
    'EmbedRequest', 'EmbedResult', 'Enum', 'ErrorEvent', 'FAILED', 'FINISH_REASONS',
    'FeatureExtractionRunner', 'Field', 'Final', 'FinishReason', 'ForwardRef', 'FrameAnalysis',
    'FrameCandidate', 'FrameContext', 'FrozenSet', 'GGUF_QUANT', 'GenerateOnce', 'GeneratedImage',
    'GenerationOutcome', 'Generator', 'Generic', 'HFAuditRow', 'HFValidationError', 'HF_CACHE',
    'HF_HOME', 'HF_HUB_CACHE', 'HF_TASK_TO_TASKS', 'HF_TOKEN', 'HF_TOKEN_ENV', 'HF_TOKEN_PATH',
    'HUGGINGFACE_DOMAIN', 'HUGPY_AUTO_DOWNLOAD', 'HUGPY_MARKER', 'HUGPY_URL', 'Hashable', 'HfApi',
    'HfHubHTTPError', 'IDENTITIES_DIR', 'IDENTITIES_HOME', 'IMG2IMG_CAPABLE_FRAMEWORKS', 'IO', 'ImageGenRequest',
    'ImageGenResult', 'ImageGenRunner', 'Img2ImgRunner', 'InputPolicy', 'ItemsView', 'Iterable',
    'Iterator', 'JOBSTATUS', 'KeysView', 'KeywordRunner', 'KeywordTaskRequest', 'KeywordTaskResult',
    'LLAMA_HOST', 'LOG_FORMAT', 'LOG_ROOT', 'LevelFilter', 'List', 'Literal',
    'LiteralString', 'LlamaCppBaseRunner', 'LlamaCppChatRunner', 'LlamaCppPythonRunner', 'LlamaCppRunner', 'LoadRefusal',
    'LocalEngineUnavailable', 'MEDIA_DEFAULTS', 'MEDIA_TYPES', 'MIME_TYPES', 'MIN_INPUT_WORDS_DEFAULT', 'MISSING',
    'MODELS', 'MODELS_DICT_PATH', 'MODELS_DIR', 'MODELS_DISCOVERY_PATH', 'MODELS_HOME', 'MODEL_CONFIG_NAME',
    'MODEL_REGISTRY', 'MODEL_REGISTRY_DICT', 'Mapping', 'MappingView', 'Match', 'MediaArtifactManifest',
    'MediaWorkspace', 'ModelConfig', 'ModelMetadata', 'MutableMapping', 'MutableSequence', 'MutableSet',
    'NEEDS_CLASSIFICATION_TASK', 'NamedTuple', 'Never', 'NewType', 'NoDefault', 'NoReturn',
    'NotRequired', 'OVERLAY_ALLOWED', 'Optional', 'OrderedDict', 'PATHS', 'PIP_CACHE_DIR',
    'PROJECTS_DIR', 'PROJECTS_HOME', 'PROJECTS_PLACEMENT_PATH', 'ParamSpec', 'ParamSpecArgs', 'ParamSpecKwargs',
    'Path', 'Pattern', 'PdfReader', 'Peer', 'Protocol', 'REGISTRY',
    'ROLES', 'RUNNER_PAIRS', 'RUNTIME_FAMILIES', 'ReadOnly', 'RepoFile', 'Required',
    'Resolution', 'ResolverFn', 'Reversible', 'Runner', 'SOURCEKIND', 'SafeFormatter',
    'Self', 'Sequence', 'Set', 'SingletonMeta', 'Sized', 'StatusEvent',
    'StreamEvent', 'SummarizeRequest', 'SummarizeResult', 'SummarizeRunner', 'SummaryPreset', 'SummaryRequest',
    'SupportsAbs', 'SupportsBytes', 'SupportsComplex', 'SupportsFloat', 'SupportsIndex', 'SupportsInt',
    'SupportsRound', 'TASK_DEFAULTS', 'TOKENIZER_SENTINEL_THRESHOLD', 'TORCH_HOME', 'TTS_TASK', 'TYPE_CHECKING',
    'TaskRequest', 'TaskResult', 'Text', 'TextIO', 'TokenCounter', 'TokenEvent',
    'TranscribeRequest', 'TranscribeResult', 'TranscribeSegment', 'TranscribeWord', 'Tuple', 'Type',
    'TypeAlias', 'TypeAliasType', 'TypeGuard', 'TypeIs', 'TypeVar', 'TypeVarTuple',
    'TypedDict', 'UPLOADS_HOME', 'Union', 'Unpack', 'VISION_HOST', 'VISION_MODELS_REGISTRY',
    'ValuesView', 'VideoAnalysisConfig', 'VideoAnalysisSummary', 'VisionBackendConfig', 'VisionRequest', 'VisionResult',
    'VisionRunner', 'WHISPER_MODELS_REGISTRY', 'WhisperRunner', 'acquire', 'adapter_base_id', 'adapter_metadata_fields',
    'adapter_peft_type', 'adapter_refusal', 'adapter_unserveable_reason', 'annotations', 'apis', 'argparse',
    'asdict', 'assert_never', 'assert_type', 'assess_config', 'attempt', 'audit_hf_snapshot',
    'audit_hfs', 'backfill_markers', 'base64', 'base_model_present', 'base_present', 'bs4',
    'build_deepcoder_config', 'build_deepcoder_runtime', 'build_resolver_chain', 'call_and_code', 'call_generate', 'candidate_model_dirs',
    'cast', 'catalog_get', 'catalog_rows', 'catching', 'caught', 'caught_block',
    'classify_model_dir', 'clean_hub_id', 'clean_invalid_newlines', 'clear', 'clear_llama_runners', 'clear_overloads',
    'combineList', 'compact_chat_request', 'compact_messages_to_budget', 'compare_lists', 'config', 'config_exists',
    'confirm_all_links', 'constants', 'contextmanager', 'copy', 'count_tokens', 'ctx_fit_chat_request',
    'ctx_fit_keep_indices', 'dataclass', 'dataclass_fields', 'dataclass_transform', 'datetime', 'deep_coder_generate',
    'default_context_tokens_for_model', 'derive_media_type', 'derive_model_config_row', 'detect_bnb_capable', 'detect_moe_capable', 'discover_model',
    'discover_models', 'download_dict_models', 'download_missing_only', 'download_one', 'download_repo', 'dump_if_json',
    'eatAll', 'eatInner', 'eatOuter', 'enrich', 'ensure_headroom_for_load', 'ensure_model',
    'ensure_models', 'ensure_nested_list', 'ensure_shard_server', 'ensure_staple_weights', 'ensure_vision_server', 'env_bool',
    'estimate_message_tokens', 'estimate_tokens', 'evict', 'evict_llama_runner', 'exclude_dirs', 'execute_chat_stream',
    'execute_prompt', 'execute_prompt_stream', 'exists', 'extension_from_content_type', 'external_runner_for', 'extract_gguf_filename',
    'field', 'field_validator', 'fields', 'filter_json_list_values', 'final', 'find_base_model_dir',
    'find_keys', 'find_keys_by_type', 'find_mmproj', 'find_original_case', 'find_paths_to_key', 'flat_destination',
    'flatten_json', 'functools', 'get_abs_name_of_this', 'get_actual_number', 'get_all_code', 'get_all_configs',
    'get_any_value', 'get_args', 'get_assessed_model_config', 'get_base_64_image', 'get_base_name', 'get_caller',
    'get_caller_dir', 'get_caller_path', 'get_code', 'get_code_from_respose', 'get_config_from_folder', 'get_config_in_dir',
    'get_context_tokens', 'get_current_path', 'get_deep_coder', 'get_desired_key_values', 'get_df', 'get_directory',
    'get_dirlist', 'get_easyocr', 'get_encoder', 'get_env_value', 'get_ext', 'get_file_name',
    'get_file_parts', 'get_file_path', 'get_files', 'get_files_and_dirs', 'get_gguf_file', 'get_glob',
    'get_guffs_in_dir', 'get_highest_value_obj', 'get_home_dir', 'get_home_folder', 'get_host', 'get_hub_id_from_directory',
    'get_huggingface_module_dir', 'get_huggingface_module_link', 'get_inputs', 'get_keybert', 'get_keys', 'get_lazy_attr',
    'get_llama_runner', 'get_logFile', 'get_max_model_length', 'get_message', 'get_messages', 'get_mime_type',
    'get_model_config', 'get_model_dirs', 'get_model_home', 'get_model_path', 'get_model_registry', 'get_model_values',
    'get_models_dict', 'get_models_dict_by_names', 'get_models_dict_by_tasks', 'get_moviepy', 'get_name', 'get_only_kwargs',
    'get_origin', 'get_overloads', 'get_paddleocr', 'get_parts', 'get_pdf2image', 'get_port',
    'get_prompt', 'get_protocol_members', 'get_pydub', 'get_pypdf2', 'get_pytesseract', 'get_request_id',
    'get_response_dir', 'get_response_path', 'get_responses_dir', 'get_safe_basename', 'get_safe_dirname', 'get_safe_splitext',
    'get_sentence_transformers', 'get_single_from_list', 'get_slash', 'get_sort', 'get_spacy', 'get_speech_recognition',
    'get_stat', 'get_symetric_difference', 'get_target_name', 'get_tiktoken', 'get_time_response_dir', 'get_torch',
    'get_transformers', 'get_type_hints', 'get_unique_part', 'get_value_from_path', 'get_whisper', 'get_worker_provider',
    'glob', 'has_hugpy_marker', 'has_standalone_config', 'hf_hub_download', 'hub_id_for', 'human_bytes',
    'imports', 'infer_arg_name', 'infer_framework', 'init_imports', 'is_adapter_dir', 'is_available',
    'is_dir', 'is_directory_excluded', 'is_file', 'is_mmproj_file', 'is_model_dir', 'is_number',
    'is_protocol', 'is_speech_checkpoint_dir', 'is_typeddict', 'is_valid_repo_id', 'itter_dir', 'join_path',
    'json', 'last_used_snapshot', 'lazy_import', 'lazy_import_single', 'lazy_module', 'legacy_task_dirs',
    'list_gguf_quants', 'list_model_options', 'list_models', 'list_set', 'loaded_disk_detail', 'loaded_model_keys',
    'loaded_runner_detail', 'loading_model_keys', 'logger', 'logging', 'makeParams', 'make_key_map',
    'make_list', 'make_list_add', 'make_list_it', 'make_request_id', 'make_response_dir', 'make_response_path',
    'make_time_response_dir', 'makedirs', 'managers', 'map_finish_reason', 'media_default_state', 'media_state',
    'media_states', 'merge_consecutive_messages', 'merge_discovery_into_models', 'merge_disk_over_registry', 'message_to_dict', 'messages_to_dicts',
    'mkdirs', 'model_looks_downloaded', 'model_serializer', 'model_validator', 'models', 'needs_classification_refusal',
    'no_makeroom_active', 'no_type_check', 'no_type_check_decorator', 'normalize_folder', 'normalize_prompt_kwargs', 'nullProxy',
    'os', 'osp', 'overload', 'override', 'parse_qs', 'parse_url',
    'peer_for', 'pick_device_and_dtype', 'pipeline_class_name', 'postRequest', 'print_hf_audit', 'prune_inputs',
    'prune_model', 'publish_catalog_changed', 'quote', 'raw_create_dirs', 're', 'read_adapter_config',
    'read_any_file', 'read_directory', 'read_file_as_text', 'read_from_file', 'read_hugpy_marker', 'read_malformed_json',
    'read_model_config', 'read_stored_hf_token', 'reap_orphaned_staging', 'record_downloaded_model', 'recursive_chunk', 'recursive_json_list',
    'refresh_registry', 'refresh_task_registries', 'remove_from_list', 'replacement', 'requested_file_missing', 'requests',
    'require', 'require_file', 'require_peft', 'resolve', 'resolve_adapter_pair', 'resolve_dir_declaration',
    'resolve_hf_model_dir', 'resolve_hub_model_info', 'resolve_hugpy_marker', 'resolve_layout_path', 'resolve_local_config', 'resolve_local_tokenizer',
    'resolve_model_dir', 'resolve_model_key', 'resolve_model_source', 'resolve_task', 'retry_on_emfile', 'reveal_type',
    'route_destination', 'run_pruned_func', 'run_unbounded', 'runner_for', 'runtime_checkable', 'runtime_folder',
    'safe_dtype_name', 'safe_dump_to_file', 'safe_dump_to_json', 'safe_join', 'safe_json_loads', 'safe_list_return',
    'safe_load_from_json', 'safe_name', 'safe_path_part', 'safe_read_from_json', 'sanitize_filename', 'save_df',
    'save_response', 'schemas', 'serve_endpoint', 'serve_model_name', 'serve_path', 'set_evict_reason',
    'set_evictable', 'set_fit_check', 'set_make_room', 'set_media_default', 'set_model_media', 'set_no_worker_diagnostic',
    'set_placement_provider', 'set_post_evict_hook', 'set_worker_boot_prewarm', 'set_worker_provider', 'set_worker_wildcard', 'slot_backed_model_keys',
    'slugify', 'snapshot_download', 'socket', 'split_hub_id', 'split_text', 'src',
    'st_mtime', 'st_size', 'staged_bytes', 'standalone_load_refusal', 'standalone_utils', 'stream_runner',
    'stream_url_to_temp_file', 'summarize', 'supported_task_keys', 'sync_marker_quants', 'sys', 'tasks_for_pipeline_class',
    'tempfile', 'threading', 'time', 'timezone', 'touch_model', 'traceback',
    'trim_content_to_token_budget', 'try_json_loads', 'unicodedata', 'unique_path', 'unprune_model', 'unquote',
    'update_model_config_dict', 'urllib', 'urlparse', 'urlunparse', 'utils', 'uuid',
    'uuid1', 'validate_file_path', 'validate_registry', 'whisper_transcribe_url_stream', 'worker_boot_prewarm_state', 'worker_wildcard_state',
    'write_hugpy_marker', 'write_to_file',
)

__all__ = [_n for _n in _SURFACE if _n in globals()]


def __getattr__(name: str):
    """Lazy fallback: anything ``from .imports/.managers/.utils import *`` bound."""
    return _aggregator_getattr(__name__, name)
