from hugpy_server.app.routes.llm_storage_routes import llm_bp
from hugpy_server.app.routes.chat_routes import chat_bp
from hugpy_server.app.routes.search_routes import search_bp
from hugpy_server.app.routes.upload_routes import upload_bp
from hugpy_server.app.routes.worker_routes import worker_bp
from hugpy_server.app.routes.v1_routes import v1_bp
from hugpy_server.app.routes.messages_routes import messages_bp
from hugpy_server.app.routes.prompt_routes import prompt_bp
from hugpy_server.app.routes.ml_routes import ml_bp
from hugpy_server.app.routes.phone_brick_routes import phone_brick_bp
from hugpy_server.app.routes.discord_routes import discord_bp
from hugpy_server.app.routes.auth_proxy_routes import auth_proxy_bp
from hugpy_server.app.routes.welcome_routes import welcome_bp
from hugpy_server.app.routes.comms_routes import comms_bp
from hugpy_server.app.routes.video_routes import video_bp
from hugpy_server.app.routes.fleet_routes import fleet_bp
from hugpy_server.app.routes.agent_routes import agent_bp
from hugpy_server.app.routes.review_routes import review_bp
from hugpy_server.app.routes.pypi_routes import pypi_bp
from hugpy_server.app.routes.eviction_routes import eviction_bp
from hugpy_server.app.routes.group_routes import group_bp
from hugpy_server.app.routes.model_group_routes import model_group_bp
from hugpy_server.app.routes.metrics_routes import metrics_bp
from hugpy_server.app.routes.oracle_routes import oracle_bp
from hugpy_server.app.routes.keeper_help_routes import keeper_help_bp
from hugpy_server.app.routes.script_first_routes import script_first_bp
from hugpy_server.app.routes.fleet_doctrine_routes import fleet_doctrine_bp
from hugpy_server.app.routes.interim_routes import interim_bp
