"""Always-on serving: llama-server specs, drivers, slots and the hot cache.

Submodules (``hot_cache``, ``slots``, ``overrides``, ``profiles``, ...) are
imported explicitly by callers; this package re-exports the serve driver API.
"""
from hugpy_engine.serve.serve import (
    DEFAULT_LLAMA_CTX,
    DEFAULT_LLAMA_NGL,
    DEFAULT_LLAMA_THREADS,
    DEFAULT_SERVE_MODE,
    LLAMA_CPP_DIR,
    LLAMA_PORT_BASE,
    LLAMA_PORT_SPAN,
    LLAMA_SERVER_BIN,
    LLAMA_SERVICE_GROUP,
    LLAMA_SERVICE_USER,
    LLAMA_SWAP_CONFIG,
    LLAMA_SWAP_HOST,
    LLAMA_SWAP_PORT,
    LLAMA_SWAP_TTL,
    LLAMA_SWAP_UNIT,
    LLAMA_UNIT_PREFIX,
    SYSTEMD_UNIT_DIR,
    OffDriver,
    RunCmd,
    ServeMode,
    ServePlan,
    ServeSpec,
    SupervisedDriver,
    SwapDriver,
    SystemdDriver,
    WriteFile,
    apply_plan,
    build_serve_specs,
    get_serve_driver,
    install_serving,
    register_serve_driver,
    serve_endpoint,
    serve_model_name,
    serve_spec_for,
    serving_overview,
    set_ctx_resolver,
    spec_row,
    start_serving,
    stop_serving,
)

__all__ = [
    "DEFAULT_LLAMA_CTX", "DEFAULT_LLAMA_NGL", "DEFAULT_LLAMA_THREADS", "DEFAULT_SERVE_MODE",
    "LLAMA_CPP_DIR", "LLAMA_PORT_BASE", "LLAMA_PORT_SPAN", "LLAMA_SERVER_BIN",
    "LLAMA_SERVICE_GROUP", "LLAMA_SERVICE_USER", "LLAMA_SWAP_CONFIG", "LLAMA_SWAP_HOST",
    "LLAMA_SWAP_PORT", "LLAMA_SWAP_TTL", "LLAMA_SWAP_UNIT", "LLAMA_UNIT_PREFIX",
    "SYSTEMD_UNIT_DIR", "OffDriver", "RunCmd", "ServeMode", "ServePlan", "ServeSpec",
    "SupervisedDriver", "SwapDriver", "SystemdDriver", "WriteFile", "apply_plan",
    "build_serve_specs", "get_serve_driver", "install_serving", "register_serve_driver",
    "serve_endpoint", "serve_model_name", "serve_spec_for", "serving_overview",
    "set_ctx_resolver", "spec_row", "start_serving", "stop_serving",
]
