"""QUERY REGISTRY — every SQL statement the model-index owns, named and in one
place (operator ruling 2026-09-10: "all db creation and calls should be
explicit", modeled on solcatcher's src/db/repositories/repos/*/query-registry).

No repository or service may inline SQL; they reference these constants. One
registry per repository, CREATE_TABLE + CREATE_INDEXES first, then the named
operations that table supports.
"""
from __future__ import annotations


class ModelQueries:
    """Canonical model records and stable links from model-index activity."""

    CREATE_TABLE = """
    CREATE TABLE IF NOT EXISTS models (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name                TEXT NOT NULL UNIQUE,
        attributes          JSONB,
        hub                 JSONB,          -- hugpy.json "hub": the full Hub record captured at download
        serving_settings    JSONB NOT NULL DEFAULT '{}'::jsonb,
        hub_id              TEXT,
        framework           TEXT,
        source_updated_at   TIMESTAMPTZ,
        created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    """

    CREATE_MODEL_WORKERS = """
    CREATE TABLE IF NOT EXISTS model_workers (
        model_id       BIGINT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
        worker_id      TEXT NOT NULL,
        allocation_rank INTEGER,
        allocation     JSONB,
        user_settings  JSONB NOT NULL DEFAULT '{}'::jsonb,
        activity       JSONB NOT NULL DEFAULT '{}'::jsonb,
        assigned       BOOLEAN NOT NULL DEFAULT false,
        fits           BOOLEAN,
        updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (model_id, worker_id)
    );
    """

    SYNC_WORKER_SETTINGS = """
    INSERT INTO model_workers
      (model_id, worker_id, allocation_rank, user_settings, updated_at)
    SELECT id, %s, %s, %s::jsonb, now() FROM models WHERE name = %s
    ON CONFLICT (model_id, worker_id) DO UPDATE
      SET allocation_rank = COALESCE(EXCLUDED.allocation_rank,
                                     model_workers.allocation_rank),
          user_settings = COALESCE(model_workers.user_settings, '{}'::jsonb)
                           || EXCLUDED.user_settings,
          updated_at = now()
    """

    FETCH_MODEL_DISPLAY = """
    SELECT m.id, m.name, m.attributes, m.serving_settings, m.hub_id, m.framework,
           m.source_updated_at,
           -- quants = the per-file FACTS (hugpy.json weights_facts mirrored into
           -- model_quant_facts, 2026-10-02): size, MoE structure, KV geometry and
           -- the precalculated ctx -> KV cost. `bytes` kept as the legacy alias.
           -- Falls back to the old model_quants listing while facts are absent.
           COALESCE((SELECT jsonb_agg((to_jsonb(f) - 'model_id' - 'sig' - 'path')
                                      || jsonb_build_object('bytes', f.size_bytes) ORDER BY f.file)
                       FROM model_quant_facts f WHERE f.model_id=m.id),
                    (SELECT jsonb_agg(to_jsonb(q) - 'model_id')
                       FROM model_quants q WHERE q.model_id=m.id), '[]'::jsonb),
           COALESCE((SELECT jsonb_agg(to_jsonb(x) - 'model_id')
                       FROM model_metrics x WHERE x.model_id=m.id), '[]'::jsonb),
           -- workers = the pair rows, each carrying its per-quant VERDICTS from
           -- model_worker_quants (2026-10-02): fits, offered modes, and the
           -- per-mode memory split (weights_gpu/weights_ram/ctx/kv_bytes) so the
           -- console prices Memory from the DB, never from central's planned_split.
           COALESCE((SELECT jsonb_agg((to_jsonb(w) - 'model_id') || jsonb_build_object(
                       'verdicts', COALESCE((SELECT jsonb_agg(jsonb_build_object(
                                     'file', v.file, 'fits', v.fits, 'modes', v.modes,
                                     'memory', v.memory, 'moe_offered', v.moe_offered,
                                     'moe', v.moe - 'why' - 'spill', 'auto', v.auto,
                                     'budget_rev', v.budget_rev, 'computed_at', v.computed_at)
                                     ORDER BY v.file)
                                     FROM model_worker_quants v
                                    WHERE v.model_id=w.model_id AND v.worker_id=w.worker_id),
                                   '[]'::jsonb)))
                       FROM model_workers w WHERE w.model_id=m.id), '[]'::jsonb),
           (SELECT jsonb_build_object('calls', count(*), 'last_at', max(c.ts))
              FROM model_calls c WHERE c.model_id=m.id)
      FROM models m
     WHERE (%s = '' OR m.name ILIKE %s OR m.hub_id ILIKE %s
            OR COALESCE(m.attributes::text, '') ILIKE %s)
     ORDER BY m.name
     LIMIT %s
    """

    FETCH_WORKER_SETTINGS = """
    SELECT m.name, w.user_settings
      FROM model_workers w
      JOIN models m ON m.id = w.model_id
     WHERE w.worker_id = %s AND m.name = ANY(%s)
    """

    SYNC_WORKER_REGISTRY_FUNCTION = """
    CREATE OR REPLACE FUNCTION hugpy_sync_worker_model_rows() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE
      model_key TEXT;
      allocation_row JSONB;
      activity_row JSONB;
      assigned_row BOOLEAN;
      worker_is_fresh BOOLEAN;
    BEGIN
      IF to_regclass('public.model_workers') IS NULL THEN
        RETURN NEW;
      END IF;
      -- FRESH worker = no pair rows yet: central's designation list seeds the
      -- DB once (operator 2026-10-02: "default for a fresh worker"). A worker
      -- the DB already knows gets NO designations from the payload — a model
      -- central still lists after a DB unassign must not come back as assigned.
      SELECT NOT EXISTS (SELECT 1 FROM model_workers WHERE worker_id = NEW.worker_id)
        INTO worker_is_fresh;
      -- DESIGNATION IS DB-OWNED (operator ruling 2026-10-02: "these should all
      -- be database relays"): the heartbeat refreshes live mechanics only
      -- (allocation/activity). ``assigned`` on an EXISTING row is the operator's
      -- decision written through the console's /assigned route and is never
      -- overwritten from central's payload; a NEW row takes its initial value
      -- from the payload (first import of a designation central already held).
      UPDATE model_workers SET allocation = NULL, activity = '{}'::jsonb,
        updated_at = now() WHERE worker_id = NEW.worker_id;

      -- A (model, worker) row exists only for a pair that is REAL on this worker:
      -- assigned (operator intent) or loading / loaded / allocated right now (live
      -- mechanics). The knob maps (moe_by_model, bnb_by_model, spill_by_model,
      -- model_last_picked) never create a row on their own: a stray pin on an
      -- unassigned model is residue, not a pairing (operator ruling 2026-10-01).
      FOR model_key IN
        SELECT value #>> '{}' FROM jsonb_array_elements(
          CASE WHEN jsonb_typeof(NEW.payload->'models')='array'
               THEN NEW.payload->'models' ELSE '[]'::jsonb END)
          WHERE jsonb_typeof(value)='string'
        UNION
        SELECT value #>> '{}' FROM jsonb_array_elements(
          CASE WHEN jsonb_typeof(NEW.payload->'loaded_models')='array'
               THEN NEW.payload->'loaded_models' ELSE '[]'::jsonb END)
          WHERE jsonb_typeof(value)='string'
        UNION
        SELECT value #>> '{}' FROM jsonb_array_elements(
          CASE WHEN jsonb_typeof(NEW.payload->'loading')='array'
               THEN NEW.payload->'loading' ELSE '[]'::jsonb END)
          WHERE jsonb_typeof(value)='string'
        UNION
        SELECT value->>'model_key' FROM jsonb_array_elements(
          CASE WHEN jsonb_typeof(NEW.payload->'allocations')='array'
               THEN NEW.payload->'allocations' ELSE '[]'::jsonb END)
          WHERE value ? 'model_key'
      LOOP
        IF model_key IS NULL OR btrim(model_key) = '' THEN CONTINUE; END IF;
        INSERT INTO models (name) VALUES (model_key)
          ON CONFLICT (name) DO NOTHING;
        allocation_row := NULL;
        SELECT value INTO allocation_row
          FROM jsonb_array_elements(
            CASE WHEN jsonb_typeof(NEW.payload->'allocations')='array'
                 THEN NEW.payload->'allocations' ELSE '[]'::jsonb END)
          WHERE value->>'model_key'=model_key LIMIT 1;
        IF allocation_row IS NULL AND
           jsonb_typeof(NEW.payload->'spill_by_model')='object' THEN
          allocation_row := NEW.payload->'spill_by_model'->model_key;
        END IF;
        -- user_settings (knobs) are DB-owned operator intent (ruling 2026-10-02:
        -- nothing live depends on central); the registry's moe_by_model /
        -- bnb_by_model maps are NOT merged in. Central reads the DB value instead.
        activity_row := jsonb_build_object(
          'loaded', COALESCE(NEW.payload->'loaded_models' ? model_key, FALSE),
          'loading', COALESCE(NEW.payload->'loading' ? model_key, FALSE));
        IF jsonb_typeof(NEW.payload->'model_last_picked')='object'
           AND NEW.payload->'model_last_picked' ? model_key THEN
          activity_row := activity_row || jsonb_build_object(
            'last_picked', NEW.payload->'model_last_picked'->model_key);
        END IF;
        assigned_row := worker_is_fresh AND COALESCE(jsonb_typeof(NEW.payload->'models')='array'
                                 AND NEW.payload->'models' ? model_key, FALSE);
        INSERT INTO model_workers
          (model_id, worker_id, allocation, user_settings, activity, assigned,
           updated_at)
        SELECT id, NEW.worker_id, allocation_row, '{}'::jsonb,
               activity_row, assigned_row, now() FROM models WHERE name=model_key
        ON CONFLICT (model_id, worker_id) DO UPDATE SET
          allocation = EXCLUDED.allocation,
          activity = EXCLUDED.activity, assigned = model_workers.assigned,
          updated_at = now();
      END LOOP;

      -- Residue: a pair that is neither assigned nor live carries nothing real.
      -- A pair central STILL LISTS keeps its (assigned=false) row until the
      -- designation relay has converged central — otherwise the next heartbeat
      -- would re-create it and the unassign would flap.
      DELETE FROM model_workers
       WHERE worker_id = NEW.worker_id AND NOT assigned AND allocation IS NULL
         AND COALESCE((activity->>'loaded')::boolean, false) = false
         AND COALESCE((activity->>'loading')::boolean, false) = false
         AND NOT (jsonb_typeof(NEW.payload->'models')='array'
                  AND NEW.payload->'models' ? (SELECT name FROM models WHERE id = model_workers.model_id));
      RETURN NEW;
    END;
    $$;
    """

    # IDEMPOTENT (2026-10-02 04:36 outage): the old DROP TRIGGER + CREATE TRIGGER
    # on every process start asked for an ACCESS EXCLUSIVE lock on the registry
    # table from a REQUEST thread. A heartbeat holding an open transaction on
    # that table (and the WorkerStore lock) was waiting for this client's lock —
    # ABBA deadlock; every other query on the DB (incl. the testshell) queued
    # behind the pending exclusive lock for 11 minutes. Now: CREATE only when
    # the trigger is missing (no DROP, so a steady-state boot takes no table
    # lock that conflicts with readers). The function body is CREATE OR REPLACE
    # and the trigger binds by name, so function changes still land.
    INSTALL_WORKER_REGISTRY_TRIGGER = """
    DO $$ BEGIN
      IF to_regclass('public.hugpy_worker_registry') IS NOT NULL
         AND NOT EXISTS (SELECT 1 FROM pg_trigger
                          WHERE tgname = 'hugpy_worker_models_sync'
                            AND tgrelid = 'public.hugpy_worker_registry'::regclass
                            AND NOT tgisinternal) THEN
        CREATE TRIGGER hugpy_worker_models_sync
          AFTER INSERT OR UPDATE OF payload ON hugpy_worker_registry
          FOR EACH ROW EXECUTE FUNCTION hugpy_sync_worker_model_rows();
      END IF;
    END $$;
    """
    # DDL must never wedge the shared connection behind another session's lock:
    # bound every schema statement's lock wait, fail that ONE call, retry later.
    DDL_LOCK_TIMEOUT_ON = "SET lock_timeout TO '5s'"
    DDL_LOCK_TIMEOUT_OFF = "SET lock_timeout TO DEFAULT"

    SYNC_MODEL_SETTINGS = """
    INSERT INTO models (name) VALUES (%s) ON CONFLICT (name) DO NOTHING;
    """

    # DETACH STEP 3 (operator 2026-10-02 06:45): models.serving_settings IS the
    # serve-overrides store; serve/overrides.py reads it here and
    # serve_overrides.json is frozen (write only with HUGPY_SERVE_OVERRIDES_JSON=1).
    FETCH_ALL_SERVING_SETTINGS = """
    SELECT name, serving_settings FROM models WHERE serving_settings <> '{}'::jsonb
    """
    UPSERT_MODEL_SETTINGS = """
    INSERT INTO models (name, serving_settings, updated_at)
    VALUES (%s, %s::jsonb, now())
    ON CONFLICT (name) DO UPDATE SET
      serving_settings = EXCLUDED.serving_settings, updated_at = now()
    """

    # Compatibility columns preserve the current query API while every child
    # row gains an enforced association to one canonical model record.
    MIGRATIONS = (
        "ALTER TABLE models ADD COLUMN IF NOT EXISTS serving_settings "
        "JSONB NOT NULL DEFAULT '{}'::jsonb;",
        "ALTER TABLE model_quants ADD COLUMN IF NOT EXISTS model_id BIGINT;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS model_id BIGINT;",
        "ALTER TABLE model_calls ADD COLUMN IF NOT EXISTS model_id BIGINT;",
        "ALTER TABLE model_workers ADD COLUMN IF NOT EXISTS assigned "
        "BOOLEAN NOT NULL DEFAULT false;",
        "ALTER TABLE model_workers ADD COLUMN IF NOT EXISTS fits BOOLEAN;",
        # PIN + PROVENANCE on the pair row (operator ruling 2026-10-02 06:05,
        # "respect the pins"): `pinned` is the operator LOCK — automation may
        # neither unassign nor retune a pinned pair; `source` is who designated
        # it (operator | wildcard | inventory | relay | benchmark; NULL =
        # unrecorded, pre-dates the column). A pin is not a third state of
        # assigned: unassign clears it, and pinning an unassigned pair is
        # refused. Replaces central's designation_meta + worker_assignments.json.
        "ALTER TABLE model_workers ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT false;",
        "ALTER TABLE model_workers ADD COLUMN IF NOT EXISTS source TEXT;",
        # who/when for the pin — own columns, NOT activity (the heartbeat
        # rewrites activity wholesale; verified 06:04 the stamp vanished in 1 s)
        "ALTER TABLE model_workers ADD COLUMN IF NOT EXISTS pinned_by TEXT;",
        "ALTER TABLE model_workers ADD COLUMN IF NOT EXISTS pinned_at TIMESTAMPTZ;",
        # PRESENCE (detach step 2, operator 2026-10-02 06:20): what is ON a
        # worker's drive, per (worker, model key), from the heartbeat — the
        # storage survey (source 'storage': bytes, store class, protected) and
        # the discovered-models report (source 'discovered': hub/framework/
        # filename/location/api). NOT an allocation: the roster's allocation
        # candidates = presence − assigned pairs; the Adopt-inventory button
        # reads it. Replaces worker_model_catalog.json. model_id is resolved when
        # the key matches a models row (NULL = worker-only model).
        """
        CREATE TABLE IF NOT EXISTS model_worker_presence (
            worker_id TEXT NOT NULL, model_key TEXT NOT NULL, model_id BIGINT,
            source TEXT NOT NULL DEFAULT 'storage',
            bytes BIGINT, store TEXT, protected BOOLEAN, detail JSONB,
            first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
            seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (worker_id, model_key));
        """,
        "ALTER TABLE models ADD COLUMN IF NOT EXISTS hub JSONB;",
        # ── facts / verdicts / budgets (one table per model, operator ruling
        # 2026-10-02) — central OWNS this DDL; the testshell only reads/writes
        # the rows. Hand-created on 2026-10-02 and re-owned to central's role;
        # from-scratch installs get them here (review finding, same day).
        "ALTER TABLE model_workers ADD COLUMN IF NOT EXISTS plan JSONB;",
        """
        CREATE TABLE IF NOT EXISTS model_quant_facts (
            model_id BIGINT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
            file TEXT NOT NULL, quant TEXT, path TEXT, size_bytes BIGINT,
            is_moe BOOLEAN, expert_bytes BIGINT, non_expert_bytes BIGINT,
            expert_count INTEGER, expert_used_count INTEGER,
            kv_geo JSONB, kv_cost JSONB, bnb_4bit JSONB, sig JSONB, error TEXT,
            version INTEGER, computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (model_id, file));
        """,
        "ALTER TABLE model_quant_facts ADD COLUMN IF NOT EXISTS kv_cost JSONB;",
        """
        CREATE TABLE IF NOT EXISTS model_worker_quants (
            model_id BIGINT NOT NULL, worker_id TEXT NOT NULL, file TEXT NOT NULL,
            fits BOOLEAN, modes JSONB, memory JSONB, auto JSONB,
            moe_offered BOOLEAN NOT NULL DEFAULT false, moe JSONB, inputs JSONB,
            version INTEGER, computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            budget_rev INTEGER, kept JSONB,
            PRIMARY KEY (model_id, worker_id, file),
            FOREIGN KEY (model_id, worker_id) REFERENCES model_workers(model_id, worker_id) ON DELETE CASCADE);
        """,
        """
        CREATE TABLE IF NOT EXISTS worker_budgets (
            worker_id TEXT PRIMARY KEY, name TEXT,
            gpu_total BIGINT, ram_total BIGINT, gpu_limit BIGINT, ram_limit BIGINT,
            vram_reserve BIGINT, ram_reserve BIGINT, gpu_budget BIGINT, ram_budget BIGINT,
            pkg_version TEXT, rev INTEGER NOT NULL DEFAULT 1, last_change JSONB,
            observed_at TIMESTAMPTZ NOT NULL DEFAULT now());
        """,
        # measured encroachment the gpu_budget is net of (2026-10-02)
        "ALTER TABLE worker_budgets ADD COLUMN IF NOT EXISTS vram_encroach BIGINT",
        SYNC_WORKER_REGISTRY_FUNCTION,
        """
        INSERT INTO models (name)
        SELECT name FROM discovery_models
        UNION SELECT model_name FROM model_quants
        UNION SELECT model_name FROM model_metrics
        UNION SELECT model_name FROM model_calls
        ON CONFLICT (name) DO NOTHING;
        """,
        """
        UPDATE models m SET attributes=d.row, hub_id=d.hub_id,
            framework=d.framework, source_updated_at=d.updated_at,
            updated_at=now()
        FROM discovery_models d WHERE d.name=m.name;
        """,
        "UPDATE model_quants q SET model_id=m.id FROM models m "
        "WHERE q.model_id IS NULL AND m.name=q.model_name;",
        "UPDATE model_metrics q SET model_id=m.id FROM models m "
        "WHERE q.model_id IS NULL AND m.name=q.model_name;",
        "UPDATE model_calls q SET model_id=m.id FROM models m "
        "WHERE q.model_id IS NULL AND m.name=q.model_name;",
        "ALTER TABLE model_quants ALTER COLUMN model_id SET NOT NULL;",
        "ALTER TABLE model_metrics ALTER COLUMN model_id SET NOT NULL;",
        "ALTER TABLE model_calls ALTER COLUMN model_id SET NOT NULL;",
        """
        DO $$ BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_constraint
              WHERE conname='model_quants_model_id_fkey'
                AND conrelid='model_quants'::regclass) THEN
            ALTER TABLE model_quants ADD CONSTRAINT model_quants_model_id_fkey
              FOREIGN KEY (model_id) REFERENCES models(id) NOT VALID;
          END IF;
          IF NOT EXISTS (SELECT 1 FROM pg_constraint
              WHERE conname='model_metrics_model_id_fkey'
                AND conrelid='model_metrics'::regclass) THEN
            ALTER TABLE model_metrics ADD CONSTRAINT model_metrics_model_id_fkey
              FOREIGN KEY (model_id) REFERENCES models(id) NOT VALID;
          END IF;
          IF NOT EXISTS (SELECT 1 FROM pg_constraint
              WHERE conname='model_calls_model_id_fkey'
                AND conrelid='model_calls'::regclass) THEN
            ALTER TABLE model_calls ADD CONSTRAINT model_calls_model_id_fkey
              FOREIGN KEY (model_id) REFERENCES models(id) NOT VALID;
          END IF;
        END $$;
        """,
        "ALTER TABLE model_quants VALIDATE CONSTRAINT model_quants_model_id_fkey;",
        "ALTER TABLE model_metrics VALIDATE CONSTRAINT model_metrics_model_id_fkey;",
        "ALTER TABLE model_calls VALIDATE CONSTRAINT model_calls_model_id_fkey;",
        "CREATE INDEX IF NOT EXISTS model_quants_model_id_idx ON model_quants (model_id);",
        "CREATE INDEX IF NOT EXISTS model_metrics_model_id_idx ON model_metrics (model_id);",
        "CREATE INDEX IF NOT EXISTS model_calls_model_id_ts_idx ON model_calls (model_id, ts DESC);",
        """
        CREATE OR REPLACE FUNCTION hugpy_link_model_by_name() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE canonical_id BIGINT;
        BEGIN
          INSERT INTO models (name) VALUES (NEW.model_name)
          ON CONFLICT (name) DO NOTHING;
          SELECT id INTO canonical_id FROM models WHERE name=NEW.model_name;
          NEW.model_id := canonical_id;
          RETURN NEW;
        END;
        $$;
        """,
        "DROP TRIGGER IF EXISTS model_quants_link_model ON model_quants;",
        "CREATE TRIGGER model_quants_link_model BEFORE INSERT OR UPDATE OF model_name ON model_quants FOR EACH ROW EXECUTE FUNCTION hugpy_link_model_by_name();",
        "DROP TRIGGER IF EXISTS model_metrics_link_model ON model_metrics;",
        "CREATE TRIGGER model_metrics_link_model BEFORE INSERT OR UPDATE OF model_name ON model_metrics FOR EACH ROW EXECUTE FUNCTION hugpy_link_model_by_name();",
        "DROP TRIGGER IF EXISTS model_calls_link_model ON model_calls;",
        "CREATE TRIGGER model_calls_link_model BEFORE INSERT OR UPDATE OF model_name ON model_calls FOR EACH ROW EXECUTE FUNCTION hugpy_link_model_by_name();",
        """
        CREATE OR REPLACE FUNCTION hugpy_sync_discovered_model() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            UPDATE models SET attributes=NULL, hub_id=NULL, framework=NULL,
                source_updated_at=NULL, updated_at=now() WHERE name=OLD.name;
            RETURN OLD;
          END IF;
          INSERT INTO models (name, attributes, hub_id, framework,
                              source_updated_at, updated_at)
          VALUES (NEW.name, NEW.row, NEW.hub_id, NEW.framework,
                  NEW.updated_at, now())
          ON CONFLICT (name) DO UPDATE SET attributes=EXCLUDED.attributes,
              hub_id=EXCLUDED.hub_id, framework=EXCLUDED.framework,
              source_updated_at=EXCLUDED.source_updated_at, updated_at=now();
          RETURN NEW;
        END;
        $$;
        """,
        "DROP TRIGGER IF EXISTS discovery_models_sync_model ON discovery_models;",
        "CREATE TRIGGER discovery_models_sync_model AFTER INSERT OR UPDATE OR DELETE ON discovery_models FOR EACH ROW EXECUTE FUNCTION hugpy_sync_discovered_model();",
        INSTALL_WORKER_REGISTRY_TRIGGER,
    )


class DiscoveryQueries:
    """discovery_models — the walk's report, one row per model."""

    CREATE_TABLE = """
    CREATE TABLE IF NOT EXISTS discovery_models (
        name        TEXT PRIMARY KEY,
        row         JSONB NOT NULL,
        hub_id      TEXT,
        framework   TEXT,
        updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    """

    CREATE_INDEXES = (
        "CREATE INDEX IF NOT EXISTS discovery_models_hub_idx "
        "ON discovery_models (hub_id);",
    )

    DELETE_ABSENT = "DELETE FROM discovery_models WHERE NOT (name = ANY(%s))"

    UPSERT_ROW = """
    INSERT INTO discovery_models (name, row, hub_id, framework, updated_at)
    VALUES (%s, %s::jsonb, %s, %s, now())
    ON CONFLICT (name) DO UPDATE
    SET row = EXCLUDED.row, hub_id = EXCLUDED.hub_id,
        framework = EXCLUDED.framework, updated_at = now()
    WHERE discovery_models.row IS DISTINCT FROM EXCLUDED.row
       OR discovery_models.hub_id IS DISTINCT FROM EXCLUDED.hub_id
       OR discovery_models.framework IS DISTINCT FROM EXCLUDED.framework
    """

    FETCH_ALL = "SELECT name, row FROM discovery_models"


class QuantQueries:
    """model_quants — one row per on-disk .gguf variant of a model."""

    CREATE_TABLE = """
    CREATE TABLE IF NOT EXISTS model_quants (
        model_name  TEXT NOT NULL,
        file        TEXT NOT NULL,
        quant       TEXT,
        bytes       BIGINT,
        shards      INT,
        PRIMARY KEY (model_name, file)
    );
    """

    CREATE_INDEXES = ()

    DELETE_ABSENT_MODELS = \
        "DELETE FROM model_quants WHERE NOT (model_name = ANY(%s))"

    DELETE_FOR_MODEL = "DELETE FROM model_quants WHERE model_name = %s"
    # change-driven sync (operator 2026-10-02: rows change only when the dir changed)
    FETCH_FOR_MODEL = "SELECT file, quant, bytes, shards FROM model_quants WHERE model_name = %s"
    DELETE_FILES_FOR_MODEL = "DELETE FROM model_quants WHERE model_name = %s AND file = ANY(%s)"

    UPSERT_VARIANT = """
    INSERT INTO model_quants (model_name, file, quant, bytes, shards)
    VALUES (%s, %s, %s, %s, %s)
    ON CONFLICT (model_name, file) DO UPDATE
    SET quant = EXCLUDED.quant, bytes = EXCLUDED.bytes,
        shards = EXCLUDED.shards
    WHERE model_quants.quant IS DISTINCT FROM EXCLUDED.quant
       OR model_quants.bytes IS DISTINCT FROM EXCLUDED.bytes
       OR model_quants.shards IS DISTINCT FROM EXCLUDED.shards
    """


class MetricsQueries:
    """model_metrics — the rollup card (model x quant x alloc_mode x worker),
    modeled on llm_storage/assets/metrics.xlsx_0.ods. tok_per_s is the LAST
    sample, tok_per_s_avg the running mean over n_samples; cold/hot load
    seconds and upload_time_s/media_bytes fill as those paths gain recording —
    absent stays NULL, never 0."""

    CREATE_TABLE = """
    CREATE TABLE IF NOT EXISTS model_metrics (
        model_name    TEXT NOT NULL,
        quant         TEXT NOT NULL DEFAULT '',
        alloc_mode    TEXT NOT NULL DEFAULT '',
        worker        TEXT NOT NULL,
        cold_load_s   DOUBLE PRECISION,
        hot_load_s    DOUBLE PRECISION,
        tok_per_s     DOUBLE PRECISION,
        tok_per_s_avg DOUBLE PRECISION,
        upload_time_s DOUBLE PRECISION,
        media_bytes   BIGINT,
        n_samples     INT NOT NULL DEFAULT 0,
        temperature   DOUBLE PRECISION,
        task          TEXT,
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        grade         DOUBLE PRECISION,
        grade_suite   TEXT,
        grade_detail  TEXT,
        graded_at     TIMESTAMPTZ,
        PRIMARY KEY (model_name, quant, alloc_mode, worker)
    );
    """

    CREATE_INDEXES = (
        "CREATE INDEX IF NOT EXISTS model_metrics_model_idx "
        "ON model_metrics (model_name);",
    )

    # Additive column migrations for tables created before the column existed
    # (CREATE TABLE IF NOT EXISTS never alters). Idempotent; run with the
    # CREATE on every process start. grade (t147, 2026-09-15): the APTITUDE
    # grade 0..100 from an active graded suite (station model_grader /
    # studio-aptitude), grade_suite names the suite, grade_detail is its
    # per-task JSON, graded_at when it was last graded.
    MIGRATIONS = (
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS grade DOUBLE PRECISION;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS grade_suite TEXT;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS grade_detail TEXT;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS graded_at TIMESTAMPTZ;",
        # Recorded cold loads (2026-09-23, review_routes._persist_cold_split):
        # the central->worker transfer and load split of a measured cold seat,
        # read back so a benchmark never cold-resets a triple it already timed.
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS transfer_s DOUBLE PRECISION;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS transfer_bytes BIGINT;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS load_s DOUBLE PRECISION;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS bytes_per_s DOUBLE PRECISION;",
        "ALTER TABLE model_metrics ADD COLUMN IF NOT EXISTS cold_measured_at TIMESTAMPTZ;",
        # INTEGRITY IS NOT APTITUDE (2026-09-23). The integrity audit
        # (hugpy_ops.model_audit --record, suite 'integrity', grade 100/0 +
        # {"verdict": ...} detail) used to be stamped across EVERY serving row
        # of a model by UPDATE_GRADE; a later benchmark result that carried no
        # valid grade then overwrote only grade_suite (COALESCE in
        # review_routes._persist_benchmark_result), leaving an integrity 100
        # labelled as an aptitude suite (e.g. 'hugpy-vision-v1'). Relabel any
        # row whose detail is an integrity verdict. Idempotent.
        "UPDATE model_metrics SET grade_suite = 'integrity'"
        " WHERE grade_suite IS DISTINCT FROM 'integrity'"
        " AND left(grade_detail, 12) = '{\"verdict\": ';",
    )

    # A tok_per_s sample advances the running average and n_samples; every
    # other field overwrites only when supplied (COALESCE keeps prior values).
    UPSERT_SAMPLE = """
    INSERT INTO model_metrics
      (model_name, quant, alloc_mode, worker, cold_load_s, hot_load_s,
       tok_per_s, tok_per_s_avg, upload_time_s, media_bytes, n_samples,
       temperature, task, updated_at)
    VALUES (%(m)s, %(q)s, %(a)s, %(w)s, %(cold)s, %(hot)s, %(tok)s, %(tok)s,
            %(up)s, %(mb)s, CASE WHEN %(tok)s IS NULL THEN 0 ELSE 1 END,
            %(temp)s, %(task)s, now())
    ON CONFLICT (model_name, quant, alloc_mode, worker) DO UPDATE SET
      cold_load_s   = COALESCE(%(cold)s, model_metrics.cold_load_s),
      hot_load_s    = COALESCE(%(hot)s,  model_metrics.hot_load_s),
      upload_time_s = COALESCE(%(up)s,   model_metrics.upload_time_s),
      media_bytes   = COALESCE(%(mb)s,   model_metrics.media_bytes),
      temperature   = COALESCE(%(temp)s, model_metrics.temperature),
      task          = COALESCE(%(task)s, model_metrics.task),
      tok_per_s     = COALESCE(%(tok)s,  model_metrics.tok_per_s),
      tok_per_s_avg = CASE WHEN %(tok)s IS NULL
                           THEN model_metrics.tok_per_s_avg
                           ELSE (COALESCE(model_metrics.tok_per_s_avg, 0)
                                 * model_metrics.n_samples + %(tok)s)
                                / (model_metrics.n_samples + 1) END,
      n_samples     = model_metrics.n_samples
                      + CASE WHEN %(tok)s IS NULL THEN 0 ELSE 1 END,
      updated_at    = now()
    """

    FETCH_BY_MODEL = """
    SELECT quant, alloc_mode, worker, cold_load_s, hot_load_s, tok_per_s,
           tok_per_s_avg, upload_time_s, media_bytes, n_samples, temperature,
           task, extract(epoch from updated_at),
           grade, grade_suite, extract(epoch from graded_at)
    FROM model_metrics WHERE model_name = ANY(%s)
    ORDER BY updated_at DESC
    """

    # A GRADE is a property of the MODEL (one aptitude, however many
    # quant/alloc/worker rows serve it), so it is stamped across every row the
    # model already has — optionally narrowed to one quant — and, when the
    # model has no row yet (graded before it was ever served), seeded as a
    # stub row (n_samples 0, no tok/s) so the grade is visible immediately.
    UPDATE_GRADE = """
    UPDATE model_metrics
       SET grade = %(g)s, grade_suite = %(s)s, grade_detail = %(d)s,
           graded_at = now(), updated_at = now()
     WHERE model_name = ANY(%(names)s)
       AND (%(q)s = '' OR quant = %(q)s)
       AND alloc_mode <> 'integrity'
    """

    # The integrity verdict has ONE row per model, keyed apart from every
    # serving row (alloc_mode 'integrity', quant/worker ''), so it can never
    # overwrite an aptitude grade nor be overwritten by one. Readers select it
    # by grade_suite = 'integrity' exactly as before.
    UPSERT_INTEGRITY = """
    INSERT INTO model_metrics
      (model_name, quant, alloc_mode, worker, n_samples,
       grade, grade_suite, grade_detail, graded_at, updated_at)
    VALUES (%(m)s, '', 'integrity', '', 0, %(g)s, 'integrity', %(d)s, now(), now())
    ON CONFLICT (model_name, quant, alloc_mode, worker) DO UPDATE SET
      grade = EXCLUDED.grade, grade_suite = EXCLUDED.grade_suite,
      grade_detail = EXCLUDED.grade_detail, graded_at = now(),
      updated_at = now()
    """

    INSERT_GRADE_STUB = """
    INSERT INTO model_metrics
      (model_name, quant, alloc_mode, worker, n_samples,
       grade, grade_suite, grade_detail, graded_at, updated_at)
    VALUES (%(m)s, %(q)s, '', %(w)s, 0, %(g)s, %(s)s, %(d)s, now(), now())
    ON CONFLICT (model_name, quant, alloc_mode, worker) DO UPDATE SET
      grade = EXCLUDED.grade, grade_suite = EXCLUDED.grade_suite,
      grade_detail = EXCLUDED.grade_detail, graded_at = now(),
      updated_at = now()
    """

    # COLD LOAD feed (t146/t147): the calibration wire is the single
    # load_seconds producer (comms.model_metrics.record_loads_from_calibration).
    # A measured cold load lands on every row this model has on that worker
    # (the serve rows carry the real alloc_mode; the load sample does not know
    # it), else on a stub row via UPSERT_SAMPLE with alloc_mode ''.
    UPDATE_COLD_LOAD = """
    UPDATE model_metrics
       SET cold_load_s = %(cold)s, updated_at = now()
     WHERE model_name = ANY(%(names)s) AND worker = %(w)s
    """


class CallQueries:
    """model_calls — the append-only per-CALL ledger (operator: "maintains its
    record of every call and its metrics"). Rows are inserted, never updated;
    model_metrics is this stream's rollup. ``state`` is the configuration
    snapshot (co-residents, vram, budget) so a row explains its own number."""

    CREATE_TABLE = """
    CREATE TABLE IF NOT EXISTS model_calls (
        id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        ts            TIMESTAMPTZ NOT NULL DEFAULT now(),
        model_name    TEXT NOT NULL,
        worker        TEXT NOT NULL,
        quant         TEXT NOT NULL DEFAULT '',
        alloc_mode    TEXT NOT NULL DEFAULT '',
        tok_per_s     DOUBLE PRECISION,
        prompt_tokens INT,
        completion_tokens INT,
        elapsed_s     DOUBLE PRECISION,
        task          TEXT,
        request_id    TEXT,
        state         JSONB
    );
    """

    CREATE_INDEXES = (
        "CREATE INDEX IF NOT EXISTS model_calls_model_ts_idx "
        "ON model_calls (model_name, ts DESC);",
        "CREATE INDEX IF NOT EXISTS model_calls_worker_idx "
        "ON model_calls (worker);",
    )

    # THE GENERATION SPLIT (2026-09-23). Additive, idempotent, run with the
    # CREATE on every process start (CREATE TABLE IF NOT EXISTS never alters):
    #   prompt_s     — prompt evaluation seconds (llama-server timings.prompt_ms)
    #   generation_s — the generation window (timings.predicted_ms; else
    #                  elapsed - prompt_s; else elapsed — see gen_basis in state)
    #   gen_tokens   — the tokens decoded INSIDE generation_s. llama-server
    #                  samples the first completion token from the prompt pass
    #                  (its time is in prompt_ms) and starts predicted_ms after
    #                  it, so an engine-timed window holds predicted_n - 1
    #                  tokens; a wall-clock window holds completion_tokens.
    # tok_per_s = gen_tokens / generation_s (NULL when either is <= 0: a
    # 1-token reply has no decode window and no rate).
    MIGRATIONS = (
        "ALTER TABLE model_calls ADD COLUMN IF NOT EXISTS prompt_s DOUBLE PRECISION;",
        "ALTER TABLE model_calls ADD COLUMN IF NOT EXISTS generation_s DOUBLE PRECISION;",
        "ALTER TABLE model_calls ADD COLUMN IF NOT EXISTS gen_tokens INT;",
    )

    INSERT_CALL = """
    INSERT INTO model_calls
      (model_name, worker, quant, alloc_mode, tok_per_s, prompt_tokens,
       completion_tokens, elapsed_s, task, request_id, state,
       prompt_s, generation_s, gen_tokens)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s, %s, %s)
    """

    FETCH_BY_MODEL = """
    SELECT extract(epoch from ts), worker, quant, alloc_mode, tok_per_s,
           prompt_tokens, completion_tokens, elapsed_s, task, request_id, state,
           prompt_s, generation_s, gen_tokens
    FROM model_calls WHERE model_name = ANY(%s)
    ORDER BY ts DESC LIMIT %s
    """

    # THROUGHPUT = Σ tokens-in-window / Σ generation seconds over EVERY
    # recorded call (never an EMA, never "the last one"), with n, the spread
    # and first/last. Per-row effective window (``gs``) and its tokens (``gt``):
    #   generation_s column (rows written since 2026-09-23)  -> gen_tokens
    #   state.generation_s (benchmark rows: the grader's copy of the reply's
    #     timings, persisted in state)                      -> state.gen_tokens
    #   state.engine_gen_s (relay rows 2026-09-23 before the column existed:
    #     llama-server predicted_ms)                         -> completion - 1
    #   state.request.ttft_s (streamed relay rows: first->last token clock)
    #                                                        -> completion - 1
    #   else the wall clock (elapsed_s)                      -> completion
    # ``basis`` names which one each row used; the stats count rows per basis
    # so a mean never hides what it is made of.
    # MEASURE ONCE: a benchmark call is recorded twice — the relay's row (the
    # serving path's measurement) and the benchmark's own grade row
    # (state.benchmark / caller 'orchestrator'). The benchmark row is the
    # TWIN and is dropped from throughput when its relay row exists: same
    # request_id, or (older rows without one) same model/worker, relay row
    # written within the call's window before it, elapsed within 1 s.
    # UNSTAMPED rows (quant '' or alloc_mode '') are counted at the worker and
    # model level and reported as their own bucket (``u``), never dropped.
    # Levels (GROUPING SETS): cell (model, worker, quant, alloc), worker
    # (model, worker), model, and the unstamped bucket per worker / per model.
    CALL_STATS = """
    WITH b AS (
      SELECT c.id, {model_expr} AS model_name,
             regexp_replace(c.model_name, '^.*~', '') AS tail,
             c.worker, c.quant, c.alloc_mode, c.ts, c.request_id,
             c.completion_tokens AS ct, c.elapsed_s AS el,
             COALESCE(c.state ? 'benchmark' OR c.state->>'caller' = 'orchestrator', false) AS bench,
             c.generation_s AS gen_col, c.gen_tokens AS gt_col,
             CASE WHEN jsonb_typeof(c.state->'generation_s') = 'number'
                  THEN (c.state->>'generation_s')::float8 END AS gen_st,
             CASE WHEN jsonb_typeof(c.state->'gen_tokens') = 'number'
                  THEN (c.state->>'gen_tokens')::float8 END AS gt_st,
             CASE WHEN jsonb_typeof(c.state->'engine_gen_s') = 'number'
                  THEN (c.state->>'engine_gen_s')::float8 END AS eng_s,
             CASE WHEN jsonb_typeof(c.state->'request'->'ttft_s') = 'number'
                  THEN (c.state->'request'->>'ttft_s')::float8 END AS ttft,
             c.state->>'gen_basis' AS basis_st
      FROM model_calls c
      WHERE TRUE {model_filter}
    ), tw AS (
      SELECT DISTINCT x.id FROM b x JOIN b r
        ON r.tail = x.tail AND r.worker = x.worker AND r.id <> x.id
       AND x.bench AND NOT r.bench
       AND ((x.request_id IS NOT NULL AND r.request_id = x.request_id)
         OR (x.request_id IS NULL AND x.el IS NOT NULL AND r.el IS NOT NULL
             AND r.ts BETWEEN x.ts - make_interval(secs => x.el + 180) AND x.ts + interval '2 seconds'
             AND abs(r.el - x.el) < 1.0))
    ), e AS (
      SELECT b.*,
        CASE WHEN gen_col IS NOT NULL THEN gen_col
             WHEN gen_st IS NOT NULL THEN gen_st
             WHEN eng_s IS NOT NULL THEN eng_s
             WHEN ttft IS NOT NULL AND el > ttft THEN el - ttft
             ELSE el END AS gs,
        CASE WHEN gen_col IS NOT NULL THEN gt_col
             WHEN gen_st IS NOT NULL THEN gt_st
             WHEN eng_s IS NOT NULL OR (ttft IS NOT NULL AND el > ttft) THEN ct - 1
             ELSE ct END AS gt,
        COALESCE(basis_st,
                 CASE WHEN gen_col IS NOT NULL OR gen_st IS NOT NULL THEN 'reported'
                      WHEN eng_s IS NOT NULL THEN 'engine'
                      WHEN ttft IS NOT NULL AND el > ttft THEN 'stream'
                      ELSE 'wall' END) AS basis,
        (quant = '' OR alloc_mode = '') AS u,
        (b.id IN (SELECT id FROM tw)) AS twin
      FROM b
    ), d AS (
      SELECT e.*, (NOT twin AND gt > 0 AND gs > 0) AS rated FROM e
    )
    SELECT model_name, worker, quant, alloc_mode, u,
           GROUPING(worker) AS g_worker, GROUPING(quant) AS g_quant, GROUPING(u) AS g_u,
           count(*) FILTER (WHERE NOT twin) AS n_calls,
           count(*) FILTER (WHERE rated) AS n_rated,
           sum(gt) FILTER (WHERE rated) AS tokens,
           sum(gs) FILTER (WHERE rated) AS seconds,
           percentile_cont(0.5) WITHIN GROUP (ORDER BY gt / gs) FILTER (WHERE rated) AS p50,
           percentile_cont(0.9) WITHIN GROUP (ORDER BY gt / gs) FILTER (WHERE rated) AS p90,
           min(gt / gs) FILTER (WHERE rated) AS mn,
           max(gt / gs) FILTER (WHERE rated) AS mx,
           min(extract(epoch from ts)) FILTER (WHERE NOT twin) AS first_at,
           max(extract(epoch from ts)) FILTER (WHERE NOT twin) AS last_at,
           sum(ct) FILTER (WHERE NOT twin AND ct > 0) AS completion_tokens,
           count(*) FILTER (WHERE NOT twin AND (ct IS NULL OR ct <= 0)) AS n_no_tokens,
           count(*) FILTER (WHERE NOT twin AND ct > 0 AND NOT rated) AS n_no_window,
           count(*) FILTER (WHERE rated AND basis IN ('engine', 'reported')) AS n_engine,
           count(*) FILTER (WHERE rated AND basis = 'stream') AS n_stream,
           count(*) FILTER (WHERE rated AND basis NOT IN ('engine', 'reported', 'stream')) AS n_wall,
           count(*) FILTER (WHERE NOT twin AND bench) AS n_bench,
           count(*) FILTER (WHERE twin) AS n_bench_twins,
           count(*) FILTER (WHERE NOT twin AND quant = '') AS n_no_quant,
           count(*) FILTER (WHERE NOT twin AND alloc_mode = '') AS n_no_alloc
    FROM d
    GROUP BY GROUPING SETS ((model_name, worker, quant, alloc_mode), (model_name, worker),
                            (model_name), (model_name, worker, u), (model_name, u))
    """

    WORKER_AVERAGES_BY_MODEL = """
    SELECT worker, avg(tok_per_s), count(*), max(extract(epoch from ts))
    FROM model_calls
    WHERE model_name = ANY(%s) AND tok_per_s IS NOT NULL
    GROUP BY worker ORDER BY avg(tok_per_s) DESC
    """


# ── Per-(model, worker) operator knobs ────────────────────────────────────
# The knobs the DB OWNS (operator ruling 2026-10-01: knobs are DB-owned, the
# console writes them here, central reads them from here — never through the
# in-memory WorkerStore). One truth: react/testshell/compute.py imports this.
PAIR_KNOB_KEYS = ("alloc_mode", "n_gpu_layers", "n_cpu_moe", "gguf_file", "moe", "bnb_4bit",
                  "threads", "llama_ctx", "serve_mode", "gpu_mem_gib", "cpu_mem_gib", "ctx_pct",
                  # CONTEXT RANGE (operator 2026-10-02): the minimum of a [min,
                  # ctx_pct] polite window the admission may shrink into before
                  # evicting; absent = no range.
                  "ctx_min_pct",
                  # KV cache knobs (operator 2026-10-02: "the actual area of
                  # adjustment that truly can make a tight load work"). The cache
                  # type is a LAUNCH choice (llama-server --cache-type-k/-v), not a
                  # property of the GGUF, so it is a per-pair knob; the stored
                  # kv_cost (priced at f16 = 2 bytes/elem) scales by the type's
                  # bytes/elem below. A quantized V cache needs flash attention.
                  "kv_cache_type", "flash_attn",
                  # explicit mode per-CLASS placement (operator 2026-10-02, layer
                  # counts not percentages — "the layer count is more explicit and
                  # true"). Nomenclature follows llama.cpp exactly:
                  #   attention_gpu_layers — the LAST N layers whose attention
                  #       (non-expert tensors) AND KV cache sit on the GPU; the KV
                  #       cache follows the layer's device, so this boundary is what
                  #       dictates where the KV spills (= --n-gpu-layers).
                  #   experts_cpu_layers   — the FIRST N layers whose expert tensors
                  #       stay in RAM (= --n-cpu-moe); >= layers - attention_gpu_layers
                  #       since a layer's experts can sit on the GPU only when its
                  #       attention does. Optional: absent, it is derived from
                  #   explicit_spill       — "prefer-gpu" (experts fill the GPU budget
                  #       left beside the attention boundary) or "prefer-ram" (every
                  #       expert in RAM). Default prefer-ram (operator 2026-10-02).
                  # The write derives n_gpu_layers / n_cpu_moe / alloc_mode=explicit
                  # onto the same row.
                  "attention_gpu_layers", "experts_cpu_layers", "explicit_spill",
                  # QUANT SELECTION (operator 2026-10-02): an ORDERED list of GGUF
                  # basenames, first preferred. The write derives gguf_file = the
                  # first listed quant whose verdict fits at the pair's ctx target
                  # + KV cache type (none fits → the head, kept and greyed in the
                  # UI). Absent/empty = the verdict default. Setting gguf_file
                  # directly drops the list (a single pick replaces it).
                  "quants",
                  # server-managed: the gguf_file the PLACEMENT knobs were tuned under
                  # (operator 2026-10-02: "each quant untouched but checked would be at
                  # default auto configs in the allocation if they were to be chosen").
                  # When the quant walk lands on a different file, the placement knobs
                  # are dropped back to auto. Not an operator knob.
                  "tuned_for")
EXPLICIT_SPILL_CHOICES = ("prefer-ram", "prefer-gpu")  # [0] = default (operator 2026-10-02: prefer-ram; the spill is a cliff, not a decline)
# placement knobs = what "auto allocation" means to clear (mirrors WorkerRow PLACEMENT_PINS)
PLACEMENT_KNOB_KEYS = ("alloc_mode", "attention_gpu_layers", "experts_cpu_layers", "explicit_spill", "moe",
                       "n_gpu_layers", "n_cpu_moe", "gpu_mem_gib", "cpu_mem_gib")


def quant_fit_walk(quants, verdict_by_file, *, ctx_pct=None, trained_by_file=None,
                   kv_cache_type="f16", bnb_on=False):
    """Pure fit-walk shared by the knob write (service) and the testshell's
    re-derivation (react/testshell/api.py). ``verdict_by_file`` maps a GGUF
    basename to its model_worker_quants ``memory`` table; a quant FITS when any
    mode in that table says fits=true AND (no ctx_pct, or that mode's
    ctx_max[kv type] holds the ctx target). Returns (chosen_file_or_None,
    {file: reason_or_None}) — the first fitting quant in list order."""
    kt = "f16" if str(kv_cache_type or "f16") == "bf16" else str(kv_cache_type or "f16")
    reasons = {}
    chosen = None
    for f in list(quants or []):
        mem = (verdict_by_file or {}).get(f)
        if mem is None:
            reasons[f] = "no verdict for this quant on this worker yet"
            continue
        table = (mem.get("bnb_4bit") or {}) if bnb_on else mem
        want = None
        trained = (trained_by_file or {}).get(f)
        if ctx_pct is not None and trained:
            want = max(1024, (int(trained) * int(ctx_pct) // 100) // 1024 * 1024)
        ok_modes = []
        for mode, mm in (table or {}).items():
            if not isinstance(mm, dict) or mm.get("fits") is not True:
                continue
            cap = (mm.get("ctx_max") or {}).get(kt)
            if want is not None and cap is not None and (int(cap) <= 0 or want > int(cap)):
                continue
            ok_modes.append(mode)
        if ok_modes:
            reasons[f] = None
            if chosen is None:
                chosen = f
        else:
            anyfit = any(isinstance(mm, dict) and mm.get("fits") is True for mm in (table or {}).values())
            reasons[f] = (f"fits, but no mode holds the context target {want} at KV {kt}" if (anyfit and want is not None)
                          else "does not fit this worker in any mode")
    return chosen, reasons

# bytes per KV element for each llama.cpp cache type (block-32 formats carry a
# 2-byte scale per 32 elements). The console's pricing uses the same table.
KV_CACHE_TYPES = {"f16": 2.0, "bf16": 2.0, "q8_0": 34 / 32, "q4_0": 18 / 32}
KV_CACHE_TYPES_NEED_FLASH = ("q8_0", "q4_0")
# AUTO mode order when the auto mode's ctx ceiling cannot hold the context
# target (operator ruling 2026-10-02): a dense GGUF that exceeds the GPU
# housing limit goes to MAX-RAM — "any touch of RAM is the cliff, so RAM is the
# ideal spill" — weights in RAM, KV on the card; max-gpu is never auto-chosen
# (an operator may still pin it).
MODE_FALLBACK_ORDER = ("gpu-only", "max-ram", "explicit", "ram-only")


class PresenceQueries:
    """model_worker_presence — the heartbeat's drive-presence snapshot per worker."""

    UPSERT = """
    INSERT INTO model_worker_presence (worker_id, model_key, model_id, source, bytes, store, protected, detail, first_seen, seen_at)
    VALUES (%s, %s, (SELECT id FROM models WHERE name = ANY(%s) ORDER BY (name = %s) DESC LIMIT 1), %s, %s, %s, %s, %s::jsonb, now(), now())
    ON CONFLICT (worker_id, model_key) DO UPDATE
       SET model_id = COALESCE(EXCLUDED.model_id, model_worker_presence.model_id),
           source = CASE WHEN EXCLUDED.source = 'discovered' OR model_worker_presence.source = 'discovered'
                         THEN 'discovered' ELSE EXCLUDED.source END,
           bytes = COALESCE(EXCLUDED.bytes, model_worker_presence.bytes),
           store = COALESCE(EXCLUDED.store, model_worker_presence.store),
           protected = COALESCE(EXCLUDED.protected, model_worker_presence.protected),
           detail = COALESCE(model_worker_presence.detail, '{}'::jsonb) || COALESCE(EXCLUDED.detail, '{}'::jsonb),
           seen_at = now()
    """
    # a COMPLETE report for a worker retires rows it no longer lists
    DELETE_STALE = """
    DELETE FROM model_worker_presence WHERE worker_id = %s AND NOT (model_key = ANY(%s))
    """
    FETCH_BY_WORKER = """
    SELECT model_key, model_id, source, bytes, store, protected, detail, first_seen, seen_at
      FROM model_worker_presence WHERE worker_id = %s ORDER BY model_key
    """
    # allocation CANDIDATES: present on the drive but not an assigned pair;
    # `fits` = any quant verdict for the pair says it fits (NULL = no verdict yet)
    FETCH_CANDIDATES = """
    SELECT p.model_key, p.model_id, p.source, p.bytes, p.store, p.protected, p.detail,
           (SELECT bool_or(q.fits) FROM model_worker_quants q
             WHERE q.model_id = p.model_id AND q.worker_id = p.worker_id) AS fits
      FROM model_worker_presence p
      LEFT JOIN model_workers w ON w.model_id = p.model_id AND w.worker_id = p.worker_id
     WHERE p.worker_id = %s AND COALESCE(w.assigned, false) = false
     ORDER BY p.model_key
    """
    # the discovered-models catalog in worker_model_catalog.json's shape
    FETCH_DISCOVERED = """
    SELECT worker_id, model_key, detail, seen_at FROM model_worker_presence WHERE source = 'discovered'
    """


class PairKnobQueries:
    """Knob reads/writes on model_workers.user_settings for ONE pair."""

    # Resolve a console model key to models.id (exact name, then the
    # owner-stripped tail — same alias forms as name_forms()).
    RESOLVE_MODEL_ID = """
    SELECT id FROM models WHERE name = ANY(%s) ORDER BY (name = %s) DESC LIMIT 1
    """

    FETCH_PAIR = """
    SELECT user_settings, plan->>'default_variant', assigned, plan->'auto'
      FROM model_workers WHERE model_id = %s AND worker_id = %s
    """

    FETCH_PAIR_VERDICTS = """
    SELECT file, moe_offered, moe, memory FROM model_worker_quants
     WHERE model_id = %s AND worker_id = %s
    """

    # Designation (DB-owned, 2026-10-02). Unassign: flip the flag and drop the
    # row when nothing live remains (no residue); assign: upsert the pair.
    # unassign also drops the pin (a pin is operator intent to have it HERE;
    # an unassigned pinned row is meaningless). RETURNING the prior pin so the
    # service can refuse an automated unassign of a pinned pair.
    SET_PAIR_ASSIGNED = """
    UPDATE model_workers SET assigned = %s, pinned = (pinned AND %s),
           pinned_by = CASE WHEN %s THEN pinned_by END, pinned_at = CASE WHEN %s THEN pinned_at END,
           updated_at = now()
     WHERE model_id = %s AND worker_id = %s
    RETURNING allocation, activity
    """
    FETCH_PAIR_PIN = """
    SELECT assigned, pinned, source FROM model_workers WHERE model_id = %s AND worker_id = %s
    """
    INSERT_PAIR_ASSIGNED = """
    INSERT INTO model_workers (model_id, worker_id, allocation, user_settings, activity, assigned, source, updated_at)
    VALUES (%s, %s, NULL, '{}'::jsonb, '{}'::jsonb, true, %s, now())
    ON CONFLICT (model_id, worker_id) DO UPDATE
       SET assigned = true, source = COALESCE(model_workers.source, EXCLUDED.source), updated_at = now()
    RETURNING allocation, activity
    """
    # pin rides an ASSIGNED row only (rowcount 0 → the service 409s).
    # params: pinned, pinned_by, pinned(for at), pinned(for source), model_id, worker_id
    SET_PAIR_PINNED = """
    UPDATE model_workers
       SET pinned = %s,
           pinned_by = %s,
           pinned_at = CASE WHEN %s THEN now() ELSE NULL END,
           source = CASE WHEN %s THEN COALESCE(source, 'operator') ELSE source END,
           updated_at = now()
     WHERE model_id = %s AND worker_id = %s AND assigned
    RETURNING pinned, source, pinned_by, pinned_at
    """
    FETCH_PAIRS_BY_WORKER = """
    SELECT w.worker_id, m.name, w.assigned, w.pinned, w.source, w.pinned_by
      FROM model_workers w JOIN models m ON m.id = w.model_id
    """
    DELETE_PAIR_RESIDUE = """
    DELETE FROM model_workers
     WHERE model_id = %s AND worker_id = %s AND NOT assigned AND allocation IS NULL
       AND COALESCE((activity->>'loaded')::boolean, false) = false
       AND COALESCE((activity->>'loading')::boolean, false) = false
    """
    FETCH_ASSIGNED_BY_WORKER = """
    SELECT w.worker_id, m.name, w.assigned FROM model_workers w JOIN models m ON m.id = w.model_id
    """

    # UPDATE-only: a knob rides an EXISTING pair row (assigned or live). A row
    # for any other pair would be residue, so rowcount 0 → the caller 409s.
    UPDATE_PAIR_KNOBS = """
    UPDATE model_workers
       SET user_settings = (COALESCE(user_settings, '{}'::jsonb) || %s::jsonb) - %s::text[],
           updated_at = now()
     WHERE model_id = %s AND worker_id = %s
    RETURNING user_settings
    """
